feat(documentation): add content for the welcome page
swisspost/design-system pull request #1116
Opened 2023-02-14 16:49 UTC by oliverschuerch

2023-02-14 16:54 UTC, swisspost-devs commented
Preview environments are getting posted here, as soon as they are ready!

2023-02-15 07:19 UTC, gfellerph requested changes

2023-02-15 07:19 UTC, gfellerph commented on packages/documentation/src/stories/welcome.stories.mdx
> +  <h2 className="h3 mb-big">Reasons to choose the Swiss Post Design System</h2>
```suggestion
  <h2 className="h3 mb-big">Features</h2>
```

2023-02-15 07:19 UTC, gfellerph commented on packages/documentation/src/stories/welcome.stories.mdx
> +  <h2 className="h3 mb-big">Technology Stack</h2>
```suggestion
  <h2 className="h3 mb-big">Technologies</h2>
```

2023-02-15 07:19 UTC, gfellerph commented on packages/documentation/src/stories/welcome.stories.mdx
> +  </div> */}
Add a todo page "Getting started" and include the primary button again or remove the commented out code.

2023-02-15 07:19 UTC, gfellerph commented on packages/documentation/src/stories/welcome.stories.mdx
> +<p>We offer different packages, which can all be used together or individually.</p>
```suggestion
```

2023-02-15 15:13 UTC, gfellerph requested changes

2023-02-15 15:13 UTC, gfellerph commented on packages/documentation/src/stories/home.stories.mdx
> +      <Feature icon="3161" title="Free">
```suggestion
      <Feature icon="2444" title="Open Source">
```

2023-02-15 15:13 UTC, gfellerph commented on packages/documentation/src/stories/home.stories.mdx
> +        <p>Open sourced on <a href="https://github.com/swisspost/design-system" target="_blank" rel="noopener">GitHub</a>, <a href="https://github.com/swisspost/design-system/blob/main/LICENSE" targe
```suggestion
        <p>Published on <a href="https://github.com/swisspost/design-system" target="_blank" rel="noopener">GitHub</a> under the <a href="https://github.com/swisspost/design-system/blob/main/LICENSE" target="_blank" rel="noopener">Apache 2.0 license</a></p>
```

2023-02-15 15:13 UTC, gfellerph commented on packages/documentation/src/stories/home.stories.mdx
> +        <p>Built with <a href="https://stenciljs.com/" target="_blank" rel="noopener">Stencil JS</a> and <a href={ `https://getbootstrap.com/docs/${getVersion('bootstrap', 'Mm')}` } target="_blank" r
```suggestion
        <p>Using modern web standards like framework agnostic web components</p>
```

2023-02-15 15:13 UTC, gfellerph commented on packages/documentation/src/stories/home.stories.mdx
> +        <p><a href="https://www.w3.org/WAI/standards-guidelines/aria/" target="_blank" rel="noopener">WAI-ARIA accessibility</a> markup</p>
```suggestion
        <p>Following the <a href="https://www.w3.org/TR/WCAG21/" target="_blank" rel="noopener">WCAG 2.1</a> guidelines</p>
```

2023-02-15 15:13 UTC, gfellerph commented on packages/documentation/src/stories/home.stories.mdx
> +</div>
I'd put that above the secondary buttons/links as it's more important.

2023-02-16 14:14 UTC, gfellerph requested changes
Just a small typo left

2023-02-16 14:14 UTC, gfellerph commented on packages/documentation/src/stories/home.stories.mdx
> +  <h2 className="h3">Packages &amp; Rescources</h2>
```suggestion
  <h2 className="h3">Packages &amp; Resources</h2>
```

2023-02-16 14:45 UTC, gfellerph approved these changes

2023-02-16 14:57 UTC, merged