fix(styles): replace lead placeholders with mixins
swisspost/design-system pull request #1143
Opened 2023-02-20 14:01 UTC by oliverschuerch

2023-02-20 14:05 UTC, swisspost-devs commented
Preview environments are getting posted here, as soon as they are ready!

2023-02-21 12:38 UTC, gfellerph requested changes
Could you add a changeset?

2023-02-21 13:30 UTC, gfellerph approved these changes
I'd change the changeset text a little to make it easier to understand for users.

2023-02-21 13:30 UTC, gfellerph commented on .changeset/five-months-unite.md
> +Replaced scss placeholder statements for .lead selector with pure mixins and variables.
```suggestion
Fixed an issue with the font size of lead text that was too small due to a specificity issue with sass placeholders.
```

2023-02-21 16:04 UTC, merged