feat(docs): add button group stories
swisspost/design-system pull request #1199
Opened 2023-02-28 18:32 UTC by alizedebray

2023-02-28 18:35 UTC, swisspost-devs commented
Preview environments are getting posted here, as soon as they are ready!

2023-03-03 10:41 UTC, gfellerph requested changes
Awesome work! I'd categorize the controls in storybook and make it a little more obvious that there are variants with checkboxes and radios.

2023-03-03 10:41 UTC, gfellerph commented on packages/documentation/src/stories/components/button-group/button-group.stories.tsx
> +      options: [' btn-sm', ' btn-rg', '', ' btn-lg'],
```suggestion
      options: [' btn-sm', ' btn-rg', '', ' btn-lg'],
      table: {
        category: 'General'
      }
```

2023-03-03 10:41 UTC, gfellerph commented on packages/documentation/src/stories/components/button-group/button-group.stories.tsx
> +      name: 'Button Elements',
```suggestion
      name: 'Variant',
```

2023-03-03 10:41 UTC, gfellerph commented on packages/documentation/src/stories/components/button-group/button-group.stories.tsx
> +        type: 'select',
```suggestion
        type: 'radio',
```

2023-03-03 10:41 UTC, gfellerph commented on packages/documentation/src/stories/components/button-group/button-group.stories.tsx
> +      options: ['button', 'link', 'checkbox', 'radio'],
```suggestion
      options: ['button', 'link', 'checkbox', 'radio'],
      table: {
        category: 'General'
      }
```

2023-03-03 10:41 UTC, gfellerph commented on packages/documentation/src/stories/components/button-group/button-group.stories.tsx
> +      options: [1, 2, 3],
```suggestion
      options: [1, 2, 3],
      table: {
        category: 'Value'
      }
```

2023-03-03 10:41 UTC, gfellerph commented on packages/documentation/src/stories/components/button-group/button-group.stories.tsx
> +      options: [1, 2, 3],
```suggestion
      options: [1, 2, 3],
      table: {
        category: 'Value'
      }
```

2023-03-03 10:41 UTC, gfellerph commented on packages/documentation/src/stories/components/button-group/button-group.stories.tsx
> +      },
```suggestion
      },
      table: {
        category: 'Content'
      }
```

2023-03-03 10:41 UTC, gfellerph commented on packages/documentation/src/stories/components/button-group/button-group.stories.tsx
> +      },
```suggestion
      },
      table: {
        category: 'Content'
      }
```

2023-03-03 10:41 UTC, gfellerph commented on packages/documentation/src/stories/components/button-group/button-group.stories.tsx
> +      },
```suggestion
      },
      table: {
        category: 'Content'
      }
```

2023-03-03 10:51 UTC, gfellerph requested changes
Can you also add a changeset with major changes for styles?

2023-03-03 10:51 UTC, gfellerph commented on packages/documentation/src/stories/components/button-group/button-group.stories.tsx
> +        <label className={`btn${args.size} btn-secondary`} htmlFor={`btncheck${position}`}>{label}</label>,
```suggestion
        <input type="checkbox" className="btn-check" id={`btncheck${position}`} autoComplete="off" defaultChecked={isSelected} key={`check${position}`} />,
        <label className={`btn${args.size} btn-secondary`} htmlFor={`btncheck${position}`} key={`checklabel${position}`}>{label}</label>,
```

2023-03-03 10:51 UTC, gfellerph commented on packages/documentation/src/stories/components/button-group/button-group.stories.tsx
> +        <label className={`btn${args.size} btn-secondary`} htmlFor={`btnradio${position}`}>{label}</label>
```suggestion
        <input type="radio" className="btn-check" name="btnradio" id={`btnradio${position}`} autoComplete="off" defaultChecked={isChecked} key={`radio${position}`} />,
        <label className={`btn${args.size} btn-secondary`} htmlFor={`btnradio${position}`} key={`radiolabel${position}`}>{label}</label>
```

2023-03-03 15:13 UTC, gfellerph approved these changes

2023-03-06 09:33 UTC, merged