feat(header): add portal config loader
swisspost/design-system pull request #1309
Opened 2023-03-27 13:22 UTC by gfellerph

2023-03-27 13:29 UTC, swisspost-devs commented
Preview environments are getting posted here, as soon as they are ready!

2023-03-28 11:53 UTC, oliverschuerch requested changes

2023-03-28 11:53 UTC, oliverschuerch commented on .changeset/afraid-bulldogs-arrive.md
> +Added the possibility to configure the header via `script` tag for Poratl specific integrations. A `lang` attribute on the html element is required for this solution to work as well as a `<script id=
```suggestion
Added the possibility to configure the header via `script` tag for Portal specific integrations. A `lang` attribute on the html element is required for this solution to work as well as a `<script id="PPM_HEADER_DATA" type="application/json">` tag containing the header config for the defined language.
```

2023-03-28 14:15 UTC, oliverschuerch approved these changes

2023-03-28 14:16 UTC, merged