feat(internet-header): add label to nav elements
swisspost/design-system pull request #1408
Opened 2023-05-15 17:49 UTC by alizedebray

2023-05-16 13:43 UTC, oliverschuerch requested changes

2023-05-16 13:43 UTC, oliverschuerch commented on packages/internet-header/src/assets/i18n/translations.ts
> +    it: 'Collegamenti intermedi',
```suggestion
  'Jump links': {
    de: 'Sprunglinks',
    fr: 'Liens de saut',
    it: 'Collegamenti di salto',
```

2023-05-16 13:43 UTC, oliverschuerch commented on packages/internet-header/src/components/post-internet-breadcrumbs/components/middle-dropdown.component.tsx
> +        <nav aria-label={translate('Intermediary links')} class="middle-dropdown">
```suggestion
        <nav aria-label={translate('Jump links')} class="middle-dropdown">
```

2023-05-16 13:43 UTC, oliverschuerch commented on packages/internet-header/src/components/post-language-switch/components/post-language-switch-list.tsx
> +    aria-labelledby="post-internet-header-language-switch-title"
```suggestion
    aria-label={config.translations.navLangAriaLabel}
```

2023-05-16 13:43 UTC, oliverschuerch commented on packages/internet-header/src/components/post-language-switch/components/post-language-switch-list.tsx
>      <ul>
```suggestion
    <ul aria-label={translate('Change language')}>
```

2023-05-16 13:43 UTC, oliverschuerch commented on packages/internet-header/src/components/post-internet-breadcrumbs/post-internet-breadcrumbs.tsx
> +            aria-labelledby="post-internet-header-breadcrumb-title"
```suggestion
          <nav
            aria-label={breadcrumbConfig.a11yLabel}
```

2023-05-16 13:47 UTC, oliverschuerch commented on packages/internet-header/src/assets/i18n/translations.ts
> +    it: 'Collegamenti intermedi',
We could also go with "skip links" in english. It should be pretty well known by users.

2023-05-16 14:15 UTC, oliverschuerch requested changes

2023-05-16 14:15 UTC, oliverschuerch commented on packages/internet-header/src/assets/i18n/translations.ts
> +    it: 'Collegamenti intermedi',
Sorry for all the changes,I didn't understand at the beginning what these translations were all about.

2023-05-17 11:50 UTC, swisspost-devs commented
Preview environments are getting posted here, as soon as they are ready!

2023-05-17 13:49 UTC, merged