fix(header): make active URL detection case insensitive
swisspost/design-system pull request #1435
Opened 2023-05-31 11:48 UTC by gfellerph

2023-05-31 11:55 UTC, swisspost-devs commented
Preview environments are getting posted here, as soon as they are ready!

2023-05-31 13:54 UTC, oliverschuerch requested changes

2023-06-01 11:18 UTC, gfellerph commented on packages/internet-header/src/services/route.service.ts
Agree, I updated the solution without modifying the input params.

2023-06-01 13:30 UTC, oliverschuerch approved these changes

2023-06-01 13:30 UTC, merged