feat(web-components): set up web components package
swisspost/design-system pull request #150
Opened 2022-06-28 14:40 UTC by gfellerph

Set up the web-components package and test the integration with cypress and jest.

2022-09-29 20:49 UTC, gfellerph commented
- [ ] Rebrand package content to design system

2022-10-03 11:02 UTC, oliverschuerch requested changes

2022-10-03 11:32 UTC, gfellerph commented on packages/components/tsconfig.json
> +    "experimentalDecorators": true,
Stencil makes heavy use of decorators, therefore yes:
https://www.typescriptlang.org/tsconfig#experimentalDecorators
https://stenciljs.com/docs/api

2022-10-03 13:46 UTC, oliverschuerch approved these changes

2022-10-03 13:49 UTC, merged