feat(styles): update buttons padding, gap and border-radius
swisspost/design-system pull request #1666
Opened 2023-07-25 14:49 UTC by imagoiq

Following https://github.com/swisspost/design-system/issues/1571#issuecomment-1641942510 and discussion from today.

Updated:
* Padding
* Internal gap
* Border-radius

Figma: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=9096%3A36684&mode=dev

2023-07-26 10:00 UTC, alizedebray requested changes
Changes work well with basic/icon buttons, only animated buttons look a bit off:
![image](https://github.com/swisspost/design-system/assets/33580481/79dee284-57da-4262-927a-db20f679773d)

From Dimitri's comment, it doesn't have to be pixel perfect, you can probably just update the `$btn-animation-distance-map` for the text and arrow placement to look like what we currently have.
![image](https://github.com/swisspost/design-system/assets/33580481/45ff72ba-c154-44ac-ad43-939195e95b39)

2023-07-26 11:27 UTC, alizedebray commented
Can you also update the icon size for large buttons, it is 24px currently instead of 22px in Figma?

2023-08-02 14:57 UTC, imagoiq commented
I think this one is ready to be merged, if you could have a look, please @gfellerph @alizedebray @oliverschuerch

2023-08-02 15:32 UTC, gfellerph requested changes
Can you add a changeset please?

2023-08-03 07:08 UTC, gfellerph approved these changes
Thx

2023-08-03 07:48 UTC, alizedebray approved these changes

2023-08-03 07:48 UTC, alizedebray commented on .changeset/polite-radios-train.md
> +Update button styles: padding, gap and border-radius
```suggestion
Update button styles: padding, gap and border-radius.
```

2023-08-03 07:51 UTC, merged