feat(documentation-v7): migrate input-group from documentation
swisspost/design-system pull request #1732
Opened 2023-08-03 13:51 UTC by b1aserlu

2023-08-04 12:34 UTC, oliverschuerch requested changes

2023-08-04 12:34 UTC, oliverschuerch commented on packages/documentation-v7/src/stories/components/input-group/input-group.docs.mdx
> +<Meta of={InputStories} />
```suggestion
import { BADGE } from '../../../../.storybook/constants';

<Meta title="Components/Input-Group" parameters={{ badges: [BADGE.TODO] }} />
```

2023-08-04 12:34 UTC, oliverschuerch commented on packages/documentation-v7/src/stories/components/input-group/input-group.stories.ts
Delete this file, because we do not need it at the moment.
Make sure you update the input-group.docs.mdx as proposed.

2023-08-08 07:50 UTC, b1aserlu commented on packages/documentation-v7/src/stories/components/input-group/input-group.stories.ts
Deleted the file as requested.

2023-08-08 08:14 UTC, oliverschuerch approved these changes

2023-08-08 12:11 UTC, merged