fix(styles): adjusts the Badge gap
swisspost/design-system pull request #1772
Opened 2023-08-09 12:23 UTC by b1aserlu

2023-08-09 12:46 UTC, oliverschuerch requested changes

2023-08-09 12:46 UTC, oliverschuerch commented on packages/styles/src/variables/components/_badge.scss
You need to add a changeset!

2023-08-09 13:15 UTC, b1aserlu commented on packages/styles/src/variables/components/_badge.scss
Added the Changeset

2023-08-09 15:10 UTC, oliverschuerch requested changes

2023-08-10 07:49 UTC, oliverschuerch approved these changes

2023-08-10 08:12 UTC, alizedebray approved these changes

2023-08-10 08:12 UTC, alizedebray commented on .changeset/ten-poets-trade.md
> +Adjusted the gap of the nested Badge
```suggestion
Adjusted the gap inside the badge.
```

2023-08-10 08:27 UTC, merged