feat(documentation-v7): migrate blockquote stories
swisspost/design-system pull request #1778
Opened 2023-08-10 09:35 UTC by b1aserlu

has some additional changes that were suggested after the previous pull request had already been merged

2023-08-10 09:43 UTC, alizedebray requested changes

2023-08-10 09:43 UTC, alizedebray commented on packages/documentation-v7/src/stories/components/blockquote/blockquote.stories.ts
> +            <cite title=${args.captionSource}>${args.captionSource}</cite>
```suggestion
            <cite>${args.captionSource}</cite>
```

2023-08-14 12:57 UTC, gfellerph approved these changes

2023-08-14 14:48 UTC, alizedebray approved these changes

2023-08-15 06:52 UTC, merged