fix(documentation, styles): Update the labels and add the visual regression test for the switch component
swisspost/design-system pull request #1885
Opened 2023-08-29 11:03 UTC by davidritter-dotcom

Closes #1816 
Closes #1170

2023-08-29 12:27 UTC, gfellerph requested changes

2023-08-29 12:27 UTC, gfellerph commented on packages/documentation/src/stories/components/switch/switch.snapshot.stories.ts
> +import meta, { Default } from './switch.stories';
```suggestion
import meta from './switch.stories';
```

2023-08-29 12:27 UTC, gfellerph commented on packages/styles/src/components/form-check.scss
This change does not belong to this PR, please revert the changes to this file.

2023-08-30 08:42 UTC, davidritter-dotcom commented on packages/styles/src/components/form-check.scss
done

2023-08-30 09:50 UTC, gfellerph approved these changes

2023-08-30 14:46 UTC, merged