fix(styles): define max-width for badges
swisspost/design-system pull request #1892
Opened 2023-08-31 07:00 UTC by davidritter-dotcom

2023-09-01 08:49 UTC, gfellerph requested changes

2023-09-01 08:49 UTC, gfellerph commented on packages/styles/src/placeholders/badge.scss
Let's discuss this! Setting a max width on the badge is the right approach, but the overflow hidden can be applied to the `<span>` containing the text inside the badge. In combination with `text-overflow: ellipsis` we also get the three dots that indicate cut text. This way, the whole positioning and padding magic is not needed.

2023-09-08 08:36 UTC, oliverschuerch commented on packages/styles/src/placeholders/badge.scss
There is no `span` element inside of the `.badge` element containing the text. And to add one would be a breaking change, because it's a CSS-only component, isn't it?

2023-09-12 12:51 UTC, oliverschuerch commented on packages/styles/src/placeholders/badge.scss
> +  position: relative;
```suggestion
```

2023-09-12 12:51 UTC, oliverschuerch commented on packages/styles/src/placeholders/badge.scss
> +  max-width: 100%;
Switch `justify-content: center` to `justify-content: start`

2023-09-12 12:51 UTC, oliverschuerch commented on packages/styles/src/placeholders/badge.scss
> +
```suggestion
```

2023-09-12 12:51 UTC, oliverschuerch commented on packages/styles/src/placeholders/badge.scss
> +    }
```suggestion
```

2023-09-12 12:51 UTC, oliverschuerch commented on packages/styles/src/placeholders/badge.scss
> +    right: badge.$badge-padding-x;
```suggestion
```

2023-09-12 12:51 UTC, oliverschuerch commented on packages/styles/src/placeholders/badge.scss
@davidritter-dotcom Philipp and I had a conversation about this and here are the outputs:
- [ ] Revert your changes.
- [ ] A Badge with a nested element (e.g. `.badge`, `.btn-close` or `.badge-check-input`) should have a `<span>` around the text. See [demo app](https://design-system.post.ch/#/bootstrap-samples/badge) for examples.
This span should not have a class on it and is not needed, if there is no other nested element.
- [ ] The outer element `<div class="badge">` should be styled with `display: inline-flex;`, `justify-content: flex-start` and `max-width: 100%`, so inner elements get aligned next to each other and the outer element can not be wider as its parent element.
- [ ] The inner elements should not be placed absolutely, so we do not need to adjust the property `padding-right` and we do also not use the `:has` selector.
- [ ] The text wrapping `<span>` needs to be styled with the css props `text-overflow: ellipsis`, `overflow: hidden` and `white-space: nowrap`, to avoid text-break and show an ellipsis when the text is to long.

- [ ] Use the same styles as used for `.badge` on the `.badge-check-label` and as used for `.badge > span` on the `.badge-check-label > span`.

2023-09-12 12:52 UTC, oliverschuerch reviewed
See comment on Philipps initial CR.

2023-09-19 09:55 UTC, oliverschuerch requested changes
Please add a changeset!

2023-09-19 09:55 UTC, oliverschuerch commented on packages/styles/src/placeholders/badge.scss
As we do manage the text-overflow on the inner `<span>` now, we can remove the `white-space: nowrap` property from the `.badge` element.

2023-09-22 06:30 UTC, oliverschuerch requested changes

2023-09-22 06:30 UTC, oliverschuerch commented on packages/documentation/src/stories/components/badge/badge.stories.ts
> +  if (!args.nestedBadge) return html`<span>${html`${args.text}`}</span>`;
```suggestion
  if (!args.nestedBadge) return html`<span>${args.text}</span>`;
```

2023-10-06 09:16 UTC, gfellerph requested changes
The overflow behaviour seems good now, there are just two suggestions I'd like to address.

2023-10-10 12:03 UTC, oliverschuerch requested changes

2023-10-10 12:03 UTC, oliverschuerch commented on packages/documentation/src/stories/components/badge/badge.stories.ts
> +  if (!args.nestedBadge) return html`<span>${args.text}</span>`;
Do we still need that?
I would suggest to implement the if statement within the return value below.
Something like

```jsx
return html`
  <span>${html`${args.text}`}</span>
  ${args.nestedBadge ? <span class="badge">10</span> : nothing}
`;
```

2023-10-17 13:06 UTC, oliverschuerch approved these changes
Great work!

2023-10-26 15:25 UTC, gfellerph approved these changes

2023-10-31 08:15 UTC, merged