feat(documentation): add visual regression test for textarea component
swisspost/design-system pull request #1899
Opened 2023-08-31 15:29 UTC by davidritter-dotcom

2023-09-01 07:37 UTC, gfellerph requested changes

2023-09-01 07:37 UTC, gfellerph commented on packages/documentation/cypress/snapshots/components/textarea.snapshot.ts
This file should actually contain the test code.

2023-09-01 07:37 UTC, gfellerph commented on packages/documentation/src/stories/components/textarea/textarea.snapshot.stories.ts
> +                .map((args: Args) => {
Reduce duplicates even further, there are more than 10 examples of the valid textarea.

<img width="745" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/8f3b2c1d-35df-4d70-8afe-3642cc9196bc">

2023-09-12 12:15 UTC, oliverschuerch commented on packages/documentation/src/stories/components/textarea/textarea.snapshot.stories.ts
Take into consideration reusing the snapshot test file for select: https://next.design-system.post.ch/iframe.html?id=snapshots--select

2023-09-15 11:36 UTC, oliverschuerch requested changes
Again, I recommend using the [select.snapshot.stories.ts](https://github.com/swisspost/design-system/blob/main/packages/documentation/src/stories/components/select/select.snapshot.stories.ts) file as a starting point and change whatever is necessary.

And to save a little bit of vertical space, we could add the attribute `rows` with a value of `1` or `2` to every textarea and only add one example with its default height per size + floating-label.

2023-10-05 06:10 UTC, oliverschuerch commented
@b1aserlu
Please merge the main branch into this branch, so we get a clean list of (in this PR) changed files only.

2023-10-05 07:21 UTC, oliverschuerch requested changes

2023-10-05 07:21 UTC, oliverschuerch commented on packages/documentation/src/stories/components/input/input.snapshot.stories.ts
> +
Remove unnecessary empty lines.

2023-10-05 07:21 UTC, oliverschuerch commented on packages/documentation/src/stories/components/select/select.snapshot.stories.ts
> +                            <h4>${args.size}</h4>
```suggestion
                            <h4>
                              ${Object.entries(context.argTypes.size.control.labels)
                                .filter(([key, value]) => key === args.size)
                                .map(s => s[1])}
                            </h4>
```

2023-10-05 07:21 UTC, oliverschuerch commented on packages/documentation/src/stories/components/select/select.snapshot.stories.ts
> +  const combinations = [
There is no example with a select option (like a filled input).

2023-10-05 07:21 UTC, oliverschuerch commented on packages/documentation/src/stories/components/textarea/textarea.snapshot.stories.ts
> +    const combinations = [
There is no example for a filled textarea.

2023-10-05 07:21 UTC, oliverschuerch commented on packages/documentation/src/stories/components/textarea/textarea.snapshot.stories.ts
> +                              <h4>${args.size}</h4>
```suggestion
                              <h4>
                              ${Object.entries(context.argTypes.size.control.labels)
                                .filter(([key, value]) => key === args.size)
                                .map(s => s[1])}
                            </h4>
```

2023-10-05 07:21 UTC, oliverschuerch commented on packages/documentation/src/utils/inputComponentsGetCombinations.ts
Remove unnecessary empty lines.

2023-10-18 13:06 UTC, b1aserlu commented
In the PR #1165 there was a problem that the snapshot test turned out to be blank I tried to fix this with the PR #2095 . As this PR handles a similar thing and will likely run in the same problem check out the changes I made and implement something similar to prevent this from happening,

2023-10-26 15:30 UTC, gfellerph approved these changes

2023-10-31 09:50 UTC, oliverschuerch requested changes

2023-10-31 09:50 UTC, oliverschuerch commented on packages/documentation/cypress/snapshots/components/input.snapshot.ts
> +
```suggestion
```

2023-10-31 09:50 UTC, oliverschuerch commented on packages/documentation/src/stories/components/select/select.snapshot.stories.ts
> +  const combinations = [
Now, every example has a selected value.

2023-11-01 09:32 UTC, oliverschuerch approved these changes

2023-11-07 13:28 UTC, merged