chore(demo, components-angular): Upgrade to Angular 16
swisspost/design-system pull request #1920
Opened 2023-09-05 08:26 UTC by imagoiq

2023-09-05 19:54 UTC, gfellerph requested changes
That looks perfect. The only thing I noticed are the ng-bootstrap documentation links on ng-bootstrap pages (beneath the title), that don't work anymore. I'm not sure why this breaks in this preview (there is an additional version segment in the URL).

Before merging, I'd also like to do a beta release to test if it's a breaking change for applications and how it plays along with the fixed dependency on Angular 15 in the styles for migrations.

- [ ] Add a changeset
- [ ] Fix ng-bootstrap documentation links
- [ ] Test with beta release in an Angular 16 application
- [ ] Update migration docs

2023-09-07 06:40 UTC, imagoiq commented
I created an Angular 16 app from scratch and integrated the component. I didn't see any issue.

2023-09-07 08:01 UTC, gfellerph commented
> I created an Angular 16 app from scratch and integrated the component. I didn't see any issue.

Nice, I'll give it a try as well, then we can decide on the version bump.

2023-09-08 14:03 UTC, gfellerph approved these changes

2023-09-12 13:51 UTC, merged