feat(documentation): adds sizing documentation
swisspost/design-system pull request #2028
Opened 2023-10-03 11:52 UTC by b1aserlu

2023-10-19 10:16 UTC, imagoiq requested changes

2023-10-19 10:16 UTC, imagoiq commented on packages/documentation/src/stories/utilities/sizing/sizing.stories.ts
> +import { html } from 'lit/static-html.js';
```suggestion
import { html } from 'lit';
```
Doesn't make a big difference, but it's more future-proof.

2023-10-19 10:16 UTC, imagoiq commented on packages/documentation/src/stories/utilities/sizing/sizing.stories.ts
> +        </ul>
Can you explain why it's needed? It confuses me.

2023-10-25 13:14 UTC, imagoiq requested changes

2023-10-25 13:14 UTC, imagoiq commented on packages/documentation/src/stories/utilities/sizing/sizing.docs.mdx
> +Height and width can be set using `h-*` and `w-*` prefixes, max-height and max-width can be set using prefixes mh-_ and mw-_ .
```suggestion
Height and width can be set using `h-*` and `w-*` prefixes, max-height and max-width can be set using prefixes `mh-*` and `mw-*` .
```

2023-10-25 13:14 UTC, imagoiq commented on packages/documentation/src/stories/utilities/sizing/sizing.docs.mdx
> +<StylesPackageImport components={['sizing']} required={{}} />
```suggestion
```
It's not a component and we don't display it on other similar docs pages like spacing.

2023-10-25 13:14 UTC, imagoiq commented on packages/documentation/src/stories/utilities/sizing/sizing.stories.ts
> +  const classes = `content h-${args.height} w-${args.width} mh-${args.maxHeight} mw-${args.maxWidth}`;
`args.maxHeight` and `args.maxWidth` can be undefined, resulting in adding class like `mh-undefined`

2023-10-25 13:14 UTC, imagoiq commented on packages/documentation/src/stories/utilities/sizing/sizing.docs.mdx
Here we are missing a `.lead` text that introduces the page.

2023-10-26 08:11 UTC, b1aserlu commented on packages/documentation/src/stories/utilities/sizing/sizing.docs.mdx
> +#### Example
No, this is only the example for the parent-based sizing the next section has its own examples

2023-10-31 14:55 UTC, imagoiq commented on packages/documentation/src/stories/utilities/sizing/sizing.docs.mdx
> +  Sizing utitlity classes are used to influence the height and width of elements to which they are
```suggestion
  Sizing utility classes are used to influence the height and width of elements to which they are
```

2023-10-31 14:56 UTC, imagoiq approved these changes

2023-11-01 09:40 UTC, b1aserlu commented on packages/documentation/src/stories/utilities/sizing/sizing.stories.ts
> +      description: 'Set the maximum width of the cube',
```suggestion
      description: 'Set the height of the rectangle',
      control: {
        type: 'select',
      },
      options: sizingOptions,
    },
    width: {
      name: 'width',
      description: 'Set the width of the rectangle',
      control: {
        type: 'select',
      },
      options: sizingOptions,
    },
    maxHeight: {
      name: 'max-height',
      description: 'Set the maximum height of the rectangle',
      control: {
        type: 'select',
      },
      options: ['none', ...sizingOptions],
    },
    maxWidth: {
      name: 'max-width',
      description: 'Set the maximum width of the rectangle',
```

2023-11-01 09:57 UTC, merged