fix(styles): add focus color on datepicker component
swisspost/design-system pull request #2061
Opened 2023-10-10 07:43 UTC by davidritter-dotcom

2023-10-10 10:53 UTC, imagoiq requested changes
Also, don't forget to lint. I would advise for doing it automatically with your IDE to avoid forgetting about it.

2023-10-10 10:53 UTC, imagoiq commented on packages/styles/src/components/datepicker.scss
> +  }
With keyboard navigation, it doesn't work (check Firefox as the default color is blue, it's more obvious).

2023-10-19 10:53 UTC, imagoiq commented on packages/styles/src/components/datepicker.scss
> +  }
This one is not compliant with WCAG. Check this article: https://www.sarasoueidan.com/blog/focus-indicators/

You need the same style as buttons.

2023-10-19 10:54 UTC, imagoiq requested changes
Need another style for the trigger button.

2023-11-16 08:37 UTC, gfellerph commented
Wait for [#1982](https://github.com/swisspost/design-system/issues/1982)

The style should be updated according to https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16545%3A53350&mode=design&t=loOePihAoe8Rf8Bz-1

2023-11-16 08:38 UTC, gfellerph requested changes
Wait for https://github.com/swisspost/design-system/issues/1982

The style should be updated according to https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16545%3A53350&mode=design&t=loOePihAoe8Rf8Bz-1

2024-02-16 14:39 UTC, gfellerph commented
@davidritter-dotcom implement with the current definition in Figma.

2024-03-20 10:08 UTC, gfellerph commented
@davidritter-dotcom design is ready. This is no longer blocked.

2024-03-20 10:46 UTC, gfellerph requested changes
Fix linting errors and update according to current Design. If that's done, please re-request review.

2024-04-03 13:18 UTC, davidritter-dotcom commented
Waiting for #2855 because of the change in the foucs-style mixin.

2024-04-05 14:01 UTC, gfellerph requested changes
There some points I noticed that don't seem to be working right now
- Focus ring should not be visible when clicking with a mouse, 
- Focus styles are not visible if a date is selected (select a date and open the picker again, the focus ring should be visible when interacting with keyboard)
- When the picker is open, the date field (and in the demo some more components) get a focus ring as well <img width="449" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/1dc63d3e-d9a8-4db5-8e71-44e208aa8f6f">. 
  This should not be the case

2024-04-12 09:14 UTC, oliverschuerch commented
@davidritter-dotcom: This task is in progress quite long now. Do you need help with something?
Do you need preciser instructions from one of the reviewer (@imagoiq and @gfellerph)?

Let me know if we can help.

2024-04-17 15:47 UTC, davidritter-dotcom commented
The focus on the select itself gets fixed when a decision is reached on how to apply focus styles to form-select and form-control.

2024-04-26 07:18 UTC, gfellerph approved these changes

2024-04-30 09:28 UTC, merged