refactor(styles): Remove bootstrap dependency on checkbox and radio
swisspost/design-system pull request #2064
Opened 2023-10-10 14:40 UTC by imagoiq

2023-10-11 14:15 UTC, imagoiq commented
Percy is green

2023-10-12 05:49 UTC, alizedebray requested changes

2023-10-12 05:49 UTC, alizedebray commented on packages/styles/src/mixins/_form-checks.scss
> +  @if ($state == 'valid' or $state == 'invalid') {
This condition is probably not necessary.
Also, this mixin is very generic and might be better in another file.

2023-10-12 05:49 UTC, alizedebray commented on packages/styles/src/variables/components/_form-check.scss
> +$form-check-inline-margin-right: spacing.$size-large !default;
Removing the "$form-check-inline-margin-left" is a breaking change, can you add the variable back to the deprecated variables in this file?

2023-10-12 05:49 UTC, alizedebray commented on packages/styles/src/components/form-validation.scss
> -      background-image: escape-svg($icon);
The background should not be removed.

2023-10-17 13:31 UTC, imagoiq commented
Percy fails on alert. Issue is visible on next. Linked issue: https://github.com/swisspost/design-system/issues/2087

2023-10-19 07:26 UTC, alizedebray approved these changes

2023-10-19 07:34 UTC, merged