fix(styles): Checked radio buttons is wrong on dark background
swisspost/design-system pull request #2065
Opened 2023-10-11 12:20 UTC by imagoiq

## What

This PR is a bit confusing as it addresses two problems.
1. Checked radio button were creating a visual shift in inline layout. It was fixed with https://github.com/swisspost/design-system/pull/2086 by using a border instead of a margin. But it created the second following problem.
2. Checked radio button on dark background blends the circle indicator with the background. #2170

Other additions:
- Added inline layout to snapshot

## UI

### Before

![image](https://github.com/swisspost/design-system/assets/12294151/a4f5b593-51b3-49aa-bbbb-cb73e39b7bae)

![image](https://github.com/swisspost/design-system/assets/12294151/1c8c2a1b-eab9-418b-ba4c-f2dff51668fa)

### After

![image](https://github.com/swisspost/design-system/assets/12294151/e2d8551b-7d5d-4474-a731-9e24f542a4f5)

![image](https://github.com/swisspost/design-system/assets/12294151/52a80a1d-ceef-4b07-b053-4d59a4aa35f2)

2023-10-24 15:18 UTC, gfellerph requested changes
Do we want to wait for the changes in #2123?

2023-10-24 15:18 UTC, gfellerph commented on packages/styles/src/components/form-check.scss
> +        border: spacing.$size-micro solid color.$white;
If a default background color scheme was defined (https://github.com/swisspost/design-system/issues/2123), we could use 

```suggestion
        border: spacing.$size-micro solid rgb(var(--post-bg-rgb));
```
and have automatic dark/light background compatibility.

2023-10-31 10:08 UTC, imagoiq commented
> Do we want to wait for the changes in #2123?

I'm not sure anymore as it's a bug. I think that it should be quickly fixed.

2023-11-07 12:58 UTC, imagoiq commented on .changeset/gorgeous-gorillas-confess.md
> +Fixed offset of radio button when checked and in inline layout.
As the second problem is caused by the first and that the first was not announced in a previous changelog, I'll stick to this sentence about the first problem.

2023-11-07 12:58 UTC, imagoiq commented on packages/styles/src/components/form-check.scss
> -        border: spacing.$size-micro solid color.$white;
The border addition was erroneously introduced in https://github.com/swisspost/design-system/pull/2086

2023-11-07 14:25 UTC, imagoiq commented on packages/components/.eslintrc.js
> +  ignorePatterns: ['.eslintrc.js'],
Fix unit tests from: https://github.com/swisspost/design-system/pull/2238/files#diff-4ade8993db0ab98cef66268e7a71355b158eefa4db4a3e03f623638800612980R14

2023-11-08 10:15 UTC, gfellerph approved these changes

2023-11-08 10:41 UTC, merged