fix(styles): Button-group checkbox/radio are visible
swisspost/design-system pull request #2133
Opened 2023-10-25 12:24 UTC by imagoiq

### What

- Fix over https://github.com/swisspost/design-system/pull/2064/files#diff-ae122d73c2e914ec29f656456684332a7282fb139cd8c3e3837a0a0b37d9b604L5 which removes Bootstrap Form-Check and includes `btn-check` styles.
- Create visual regression tests for button-group

Closes #2084 

### UI 

#### Before

![image](https://github.com/swisspost/design-system/assets/12294151/d640b82b-42b6-4620-83ec-953490c31dd6)

2023-10-31 13:28 UTC, alizedebray requested changes
A focus shadow is missing for checkbox and radio buttons

2023-10-31 13:28 UTC, alizedebray commented on packages/documentation/src/stories/components/button-group/button-group.stories.ts
> +      const isSelected = position === args.selected;
This does not work with checkboxes

2023-10-31 14:01 UTC, imagoiq commented
> A focus shadow is missing for checkbox and radio buttons

Yes this is the ticket: https://github.com/swisspost/design-system/issues/2134

2023-10-31 14:43 UTC, imagoiq commented on packages/documentation/src/stories/components/button-group/button-group.stories.ts
> +      const isSelected = position === args.selected;
Fixed!

2023-11-02 14:43 UTC, alizedebray approved these changes

2023-11-06 07:15 UTC, merged