chore(*): Fix eslint configs
swisspost/design-system pull request #2140
Opened 2023-10-26 12:25 UTC by imagoiq

2023-10-30 07:53 UTC, imagoiq commented on packages/components/.eslintrc.js
> +    tsconfigRootDir: __dirname,
Convert to js to be able to use `__dirname`

2023-10-31 09:01 UTC, alizedebray approved these changes

2023-10-31 09:14 UTC, gfellerph requested changes
Looking good so far

2023-10-31 09:59 UTC, imagoiq commented on packages/components/.eslintrc.js
> +module.exports = {
Unfortunately, it's not as easy as that. I think the error only appears in your IDE, but not the tools. We need to make a lot of changes so I created another ticket for that: https://github.com/swisspost/design-system/issues/2167

2023-10-31 10:06 UTC, imagoiq commented on packages/internet-header/.eslintignore
> +jest.config.js
Yes, you're right. For the other, there are some weird issues with the stencil-community plugin.

2023-10-31 10:33 UTC, imagoiq commented on packages/components/tsconfig.eslint.json
> +  "include": ["src", "**/tests"],
I cannot reproduce it. Where does the error appear?

2023-10-31 13:38 UTC, gfellerph commented on packages/components/tsconfig.eslint.json
> +  "include": ["src", "**/tests"],
It only appears when the above suggestion is applied, so it will be fixed with #2167

2023-10-31 13:39 UTC, gfellerph approved these changes

2023-10-31 13:40 UTC, merged