feat(demo): demo add link to beta storybook
swisspost/design-system pull request #2142
Opened 2023-10-26 13:50 UTC by davidritter-dotcom

2023-10-31 09:52 UTC, gfellerph requested changes
Added a little more rockets

2023-10-31 12:16 UTC, davidritter-dotcom commented on packages/demo/src/app/home/home.component.html
> +      </p>
I like the rocket, but is it supposed to go in the alert about Angular 16, shouldn't it be in the new alert about migreating towards storybook?

2023-11-01 16:46 UTC, gfellerph requested changes
1. 
<img width="1242" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/77d8f39c-b00a-4f39-92df-e8cc65a708fb">

The button is on the wrong alert.

2. There are 325 binary files from the angular compilation checked in (packages/components-angular/.angular/...) please untrack them https://stackoverflow.com/questions/18357511/git-remove-committed-file-after-push, please ask if you need help here.

2023-11-08 10:17 UTC, gfellerph requested changes
@davidritter-dotcom, please add a changeset for the demo "Added link to new documentation" or something along these lines.

2023-11-16 08:52 UTC, gfellerph approved these changes

2023-11-21 08:18 UTC, merged