fix: stencil empty output files
swisspost/design-system pull request #2214
Opened 2023-11-03 12:25 UTC by oliverschuerch

This time without the breaking changes, which we had to revert the last time ;) #2208

2023-11-07 11:38 UTC, gfellerph requested changes

2023-11-07 11:38 UTC, gfellerph commented on packages/documentation/src/stories/getting-started/components/components.docs.mdx
It would be nice to re-structure this page a little and maybe use tabs. This would clear things up a bit and I think 95% of use cases will be for the framework integration.

```
__________________________________________________
| Framework integration | JavaScript integration |______________
```

2023-11-07 15:55 UTC, oliverschuerch commented on packages/documentation/src/stories/getting-started/components/components.docs.mdx
This is coming with the PR #2071

2023-11-07 15:59 UTC, oliverschuerch commented on packages/internet-header/stencil.config.ts
Added it back in both, internet-header and components package

2023-11-08 10:22 UTC, gfellerph approved these changes
Nice work!

2023-11-08 10:23 UTC, merged