feat(demo): Adds depreaction message for dismissible alerts
swisspost/design-system pull request #2239
Opened 2023-11-07 10:27 UTC by b1aserlu

2023-11-09 14:11 UTC, alizedebray requested changes

2023-11-09 14:11 UTC, alizedebray commented on packages/demo/src/app/ng-bootstrap/components/alert/alert-demo-page/alert-demo-page.component.html
The deprecation message should be displayed on the bootstrap alert page: https://design-system.post.ch/#/bootstrap-samples/alerts,not on the ng-bootstrap page.

We do not want static alerts to be dismissible because the animation is then missing but ng-bootstrap handles the animation as well as the web component.

2023-11-09 14:11 UTC, alizedebray commented on packages/demo/src/app/ng-bootstrap/components/alert/alert-demo-page/alert-demo-page.component.html
> +    With the next version of the swiss post desing system there will be a
The web component is already available.

2023-11-09 14:11 UTC, alizedebray commented on .changeset/mean-meals-train.md
> +Dismissible alerts are deprecated and will be removed next version.
```suggestion
Deprecated standard HTML alerts with a close button in favor of the `post-alert` component designed to correctly handle the dismissal animation.
```

2023-11-14 10:14 UTC, b1aserlu commented on packages/demo/src/app/bootstrap/components/alert/alert-demo-page/alert-demo-page.component.html
> +      that will handle dissmissable alerts. HTMl alerts should only be used for static alerts.
```suggestion
      that will handle dissmissable alerts. HTML alerts should only be used for static alerts.
```

2023-11-17 16:07 UTC, alizedebray approved these changes

2023-11-17 16:07 UTC, alizedebray commented on packages/demo/src/app/bootstrap/components/alert/alert-demo-page/alert-demo-page.component.html
> +      that will handle dissmissable alerts. HTML alerts should only be used for static alerts.
```suggestion
      that will handle dissmissible alerts. HTML alerts should only be used for static alerts.
```

2023-11-22 11:00 UTC, merged