feat(styles, docs): Update select styles
swisspost/design-system pull request #2312
Opened 2023-11-28 14:44 UTC by imagoiq

2023-11-28 14:45 UTC, imagoiq commented on packages/styles/src/variables/components/_forms.scss
> +  box-shadow 0.15s ease-in-out !default;
Just some linting as in some other lines

2023-12-01 14:03 UTC, gfellerph requested changes
Looks good! Just small things to fix.

2023-12-01 14:03 UTC, gfellerph commented on packages/documentation/src/stories/components/select/select.stories.ts
You could add `success: false` to the args settings, then there will be a switch by default instead of this button "set boolean".

2023-12-01 14:03 UTC, gfellerph commented on packages/styles/src/components/form-select.scss
> +    background-image: b.escape-svg(form-select.$form-select-indicator-success),
<img width="592" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/444c10bd-9d05-4b84-ad39-0abf31dbb9ed">

The distance between the two icons is not big enough. As they look really similar it's confusing to look at.

2023-12-06 10:02 UTC, gfellerph approved these changes

2023-12-06 11:40 UTC, merged