feat(styles): Update forms styles
swisspost/design-system pull request #2396
Opened 2023-12-13 12:52 UTC by imagoiq

### What
- Update form-control, form-select sizes to match Figma
- Update floating label color of form-control to match Figma

### Review
Check all similar components: e.g. Textarea, File Input, …

2023-12-21 15:12 UTC, oliverschuerch reviewed
The text of the small select variant gets cropped (see letter `p`) and the vertical alignment looks wrong (at least in chrome). I think we need to reduce the line-height there or for all small variants.
![image](https://github.com/swisspost/design-system/assets/9716662/95eb4263-cb0c-4436-b31b-9c5d4e80cf1d)

2023-12-21 15:25 UTC, oliverschuerch requested changes
Both stories (select and input) should set the `size` control to the `large` value. As this will be the new default size.

2024-01-17 12:00 UTC, oliverschuerch requested changes
We should remove the deprecated sizes (`Regular` and `Middle`) from the size control in storybook and describe the deprecation of them in a alert before or after the controls.

They still need to work

This would also enable us to use the size without a class as the new default.

Mapping:
| Old size | New Size | CssClass |
| - | - | - |
| `Small` | `Small` | `form-control-sm` |
| `Regular` | deprecated | `form-control-rg` |
| `Middle` | `Large` | `none`
| `Large` | deprecated | `form-control-lg` |

What do you think?

2024-01-17 13:26 UTC, imagoiq commented
> We should remove the deprecated sizes (`Regular` and `Middle`) from the size control in storybook and describe the deprecation of them in a alert before or after the controls.
> 
> They still need to work
> 
> This would also enable us to use the size without a class as the new default.
> 
> Mapping:
> Old size 	New Size 	CssClass
> `Small` 	`Small` 	`form-control-sm`
> `Regular` 	deprecated 	`form-control-rg`
> `Middle` 	`Large` 	`none`
> `Large` 	deprecated 	`form-control-lg`
> 
> What do you think?

Sure, but it will be handled with https://github.com/swisspost/design-system/issues/2225

2024-01-17 13:27 UTC, imagoiq commented on packages/documentation/src/stories/components/forms/input/input.stories.ts
I agree, but they will automatically disappear when we'll remove the deprecated size, so it is easier to wait then to workaround for the meantime.

2024-01-17 14:00 UTC, oliverschuerch commented on packages/documentation/src/stories/components/forms/input/input.stories.ts
We will only remove this deprecated sizes when we release v7, which could be at the end of this year or even later. So in the meantime I prefer to not confuse our users with non existing input sizes.

2024-01-17 16:05 UTC, oliverschuerch commented
> > We should remove the deprecated sizes (`Regular` and `Middle`) from the size control in storybook and describe the deprecation of them in a alert before or after the controls.
> > They still need to work
> > This would also enable us to use the size without a class as the new default.
> > Mapping:
> > Old size 	New Size 	CssClass
> > `Small` 	`Small` 	`form-control-sm`
> > `Regular` 	deprecated 	`form-control-rg`
> > `Middle` 	`Large` 	`none`
> > `Large` 	deprecated 	`form-control-lg`
> > What do you think?
> 
> Sure, but it will be handled with #2225

Sure, but this is a breaking change who will be implemented in the far future.

2024-01-23 15:24 UTC, imagoiq commented on packages/documentation/src/stories/components/forms/input/input.stories.ts
Sorry I thought that you were speaking about the snapshots, but you are speaking about the controls. I don't see how to do it using if condition in the argtypes especially as you cannot have multiple if (https://github.com/storybookjs/storybook/issues/21281). Do you have any idea?

2024-01-30 10:06 UTC, oliverschuerch approved these changes

2024-01-30 15:05 UTC, merged