fix(demo): Links to new icons documentation are broken
swisspost/design-system pull request #2402
Opened 2023-12-13 16:36 UTC by imagoiq

2023-12-21 14:55 UTC, oliverschuerch requested changes

2023-12-21 14:55 UTC, oliverschuerch commented on packages/demo/src/app/post-sample/components/icons/icons-demo-page/icons-demo-page.component.html
To me it looks, like we should switch the links:
brand new icons documentation: links over to the icon search, not to the getting started page
discover the new icons: links over to the getting started page, not to the icon search.

What do you think?

2024-01-08 08:12 UTC, imagoiq commented on packages/demo/src/app/post-sample/components/icons/icons-demo-page/icons-demo-page.component.html
Here it is

2024-01-09 15:02 UTC, oliverschuerch approved these changes

2024-01-09 15:14 UTC, merged