fix(styles): removes unwanted margin for heading in layouts/portal
swisspost/design-system pull request #2407
Opened 2023-12-14 09:51 UTC by b1aserlu

2024-01-16 12:26 UTC, imagoiq requested changes
Thanks for the proposal, but it's only a workaround. The issue is that the styles are different between the index and intranet bundles (see https://next.design-system.post.ch/?path=/docs/getting-started-styles--docs). Can you please check with Philipp? Or assign the issue to him. Last time that I talked about this issue, he had some ideas.

2024-01-25 14:09 UTC, b1aserlu commented
Asigned Issue to Phillip

2024-02-16 14:33 UTC, gfellerph commented
See https://github.com/swisspost/design-system/issues/1931#issuecomment-1948478202. A temporary resolution to this problem would be my preferred way of dealing with it.

2024-02-16 14:35 UTC, gfellerph requested changes

2024-02-16 14:35 UTC, gfellerph commented on packages/styles/src/layouts/portal/_type.scss
> +    }
This selector is too generic, scope it to the notification overlay title, no matter what heading level.

2024-02-16 14:35 UTC, gfellerph commented on .changeset/spotty-countries-smoke.md
> +Removes unwanted margin from heading when using `@use "@swisspost/design-system-styles/index.scss";`
```suggestion
Removes unwanted margin from heading within the notification overlay component.
```

2024-02-26 05:53 UTC, merged