chore(contribution.md): adds definiton of done
swisspost/design-system pull request #2422
Opened 2023-12-19 14:30 UTC by b1aserlu

2024-01-18 13:53 UTC, oliverschuerch requested changes

2024-01-18 13:53 UTC, oliverschuerch commented on CONTRIBUTING.md
> +
```suggestion
```

2024-01-18 13:53 UTC, oliverschuerch commented on CONTRIBUTING.md
> +#### Definition of Done for a Story
```suggestion
### Definition of Done for a Story
```

2024-01-18 13:53 UTC, oliverschuerch commented on CONTRIBUTING.md
> +- Component docs
Could you convert all the top-level items (Component docs, Controls, Testing, etc.) to a h4 (e.g. #### Component docs)?

2024-01-22 10:20 UTC, gfellerph requested changes

2024-01-22 10:20 UTC, gfellerph commented on CONTRIBUTING.md
> +  - Possibility to re-create all variants (good for debugging because they can be set via query params and a reproduction can be linked)
```suggestion
  - Possibility to showcase and test all variants of the component. This enables re-usage of the docs programmatically for visual regression testing.
```

2024-01-22 10:20 UTC, gfellerph commented on CONTRIBUTING.md
> +  - For more complex widgets: screen reader testing (at least nvda)
```suggestion
  - Screen reader testing (at least nvda)
```

2024-01-22 10:20 UTC, gfellerph commented on CONTRIBUTING.md
> +  - Cross browser testing of the docs
```suggestion
  - Cross browser testing of the docs (official Post supported browsers -> https://github.com/swisspost/design-system/blob/main/packages/styles/.browserslistrc)
```

2024-01-22 10:20 UTC, gfellerph commented on CONTRIBUTING.md
> +    - Try emulating the high contrast mode in chrome by yourself:
```suggestion
    - Emulating the high contrast mode in chrome:
```

2024-01-22 10:20 UTC, gfellerph commented on CONTRIBUTING.md
> +  - No `react related attributes in code snippets (e.g. className, htmlFor, key, etc.)
```suggestion
  - No react related attributes in code snippets (e.g. className, htmlFor, key, etc.)
```

2024-01-22 10:20 UTC, gfellerph commented on CONTRIBUTING.md
> +  - No nested p's (beware of .lead and .alert)
```suggestion
  - No nested `<p>` tags (beware of .lead and .alert)
```

2024-01-22 10:20 UTC, gfellerph commented on CONTRIBUTING.md
> +  - When using LinkTo use both kind and story attributes
```suggestion
  - When using LinkTo use both the `kind` and `story` attributes
```

2024-01-22 10:20 UTC, gfellerph commented on CONTRIBUTING.md
> +  - `div.hide-col-default` wrapper for Controls component on CSS only docs
```suggestion
  - `div.hide-col-default` wrapper for controls on CSS only component docs
```

2024-01-22 10:20 UTC, gfellerph commented on CONTRIBUTING.md
> +  - Add the `sourceState="shown"` attribute to the first canvas if the code is not too long.
```suggestion
  - Add the `sourceState="shown"` attribute to the first canvas if the code is not too long (less than 8 lines)
```

2024-01-22 10:20 UTC, gfellerph commented on CONTRIBUTING.md
> +  - style file `[component].styles.scss`
```suggestion
  - Style file `[component].styles.scss`
```

2024-01-22 10:20 UTC, gfellerph commented on CONTRIBUTING.md
> +    For example use mapClasses utility function instead of `[*].filter(c => c && c !== 'null').join(' ')`
```suggestion
    For example use the `mapClasses` utility function instead of `[*].filter(c => c && c !== 'null').join(' ')`.
```

2024-02-08 16:13 UTC, imagoiq commented on CONTRIBUTING.md
> +- Testing in High Contrast mode
```suggestion
- Testing the High Contrast mode
```

2024-02-08 16:13 UTC, imagoiq commented on CONTRIBUTING.md
> +- Cross browser testing of the docs (official Post supported browsers -> https://github.com/swisspost/design-system/blob/main/packages/styles/.browserslistrc)
Maybe this is something to be reviewed since: https://github.com/swisspost/design-system/issues/2425

2024-02-08 16:13 UTC, imagoiq commented on CONTRIBUTING.md
> +    - You can switch also prefers-color-scheme to test light/dark mode.
This is not something that I'm expecting to be written here as I'm not a chrome user and you don't want to list all possibilities.

2024-02-08 16:13 UTC, imagoiq commented on CONTRIBUTING.md
> +- `aria-hidden="true"` or span.visually-hidden labels for all icons
```suggestion
- `aria-hidden="true"` or `span.visually-hidden` labels for all icons
```

2024-02-08 16:13 UTC, imagoiq commented on CONTRIBUTING.md
> +- Screen reader testing (at least nvda)
```suggestion
- Screen reader testing (at least nvda+win)
```
In the screen reader context, the combination of OS + screen reader matters.

2024-02-13 07:28 UTC, gfellerph approved these changes

2024-02-14 08:20 UTC, oliverschuerch approved these changes

2024-02-14 08:21 UTC, merged