fix(docs): Convert LinkTo to regular links
swisspost/design-system pull request #2496
Opened 2024-01-15 14:00 UTC by imagoiq

2024-01-18 07:14 UTC, imagoiq commented
> We have a lot of links included in the stories files, which are broken. Would be nice to fix them as well in this PR.
> 
> Example: alert.stories.ts -> meta.argTypes.icon.description
> 
> An even better idea could be to add a e2e test in documentation, which goes trough every a-tag and checks if the url in the href can be loaded. What do you think, should we open a ticket for this?

For the record, I opened this ticket https://github.com/swisspost/design-system/issues/2465

I fixed the broken links in meta (at least the one that I've found).

2024-01-18 14:36 UTC, oliverschuerch commented
Please update to the newest `main` branch, as the documentation isn't running correctly.

2024-01-18 14:36 UTC, oliverschuerch requested changes
Please update to the newest main branch, as the documentation isn't running correctly.

2024-01-23 14:52 UTC, imagoiq commented on packages/documentation/src/stories/components/forms/choice-card/choice-card.ts
> +        'When set to `true`, disables the component\'s functionality and places it in a disabled state.<span className="mt-mini alert alert-info alert-sm">There are accessibility concerns with the di
In those controls, html seem to no work anymore. I don't get it. @oliverschuerch do you have an idea?

2024-01-23 15:45 UTC, oliverschuerch approved these changes

2024-01-24 09:18 UTC, merged