feat(docs): add datepicker documentation
swisspost/design-system pull request #2518
Opened 2024-01-19 14:55 UTC by alizedebray

2024-01-22 10:36 UTC, imagoiq commented on packages/documentation/src/shared/nb-bootstrap/ngb-component-alert.mdx
> +  <p className="alert-heading">The datepicker is an ng-bootstrap component.</p>
```suggestion
  <p className="alert-heading">The {props.component} is an ng-bootstrap component.</p>
```

2024-01-22 10:37 UTC, gfellerph requested changes
Great work! This can be used as a reference for the other docs.

2024-01-22 10:37 UTC, gfellerph commented on .changeset/angry-islands-shout.md
> +Added a documentation page for the datepicker component.
```suggestion
Added a documentation page for the ng-bootstrap datepicker component.
```

2024-01-22 10:37 UTC, gfellerph commented on packages/documentation/.storybook/helpers/bages-config.ts
> +      desc: 'This component may be replaced by a web component in a future release.',
```suggestion
      desc: 'This component may be replaced by a web component in the future.',
```

2024-01-22 10:37 UTC, gfellerph commented on packages/documentation/src/shared/nb-bootstrap/ngb-component-demo-link.mdx
We could also place this button in the info box, I think it's a little bit more visible there. Previous docs could be the primary action and ng bootstrap docs the secondary.

![image](https://github.com/swisspost/design-system/assets/1659006/89abe538-e756-419e-9d2f-1e2f6aef7d65)

2024-01-22 10:37 UTC, gfellerph commented on packages/documentation/src/shared/nb-bootstrap/ngb-component-demo-link.mdx
> +  href={`https://design-system.post.ch/#/ng-bootstrap-samples/${props.component}`}
This link will change to something like https://**demo**.design-system.post.ch/#/bla, but we'll update that in a separate step when the environment is set up.

2024-01-22 10:43 UTC, imagoiq approved these changes

2024-01-22 10:43 UTC, imagoiq commented on packages/documentation/.storybook/styles/preview.scss
> +  }
It could be nice to have a comment here.

2024-01-22 10:43 UTC, imagoiq commented on packages/documentation/src/shared/nb-bootstrap/ngb-component-internationalization.mdx
> +The internationalization of this content is done using the @angular/localize package.
```suggestion
The internationalization of this content is done using the `@angular/localize` package.
```

2024-01-22 10:43 UTC, imagoiq commented on packages/documentation/src/stories/components/datepicker/datepicker.docs.mdx
> +</ul>
Those don't work anymore since https://github.com/swisspost/design-system/pull/2467. But it's not a blocker for this PR.

2024-01-22 12:57 UTC, imagoiq commented on packages/documentation/src/shared/nb-bootstrap/ngb-component-demo-link.mdx
> +  href={`https://design-system.post.ch/#/ng-bootstrap-samples/${props.component}`}
```suggestion
  href={`https://archive.design-system.post.ch/#/ng-bootstrap-samples/${props.component}`}
```

2024-01-23 08:30 UTC, alizedebray commented on packages/documentation/src/shared/nb-bootstrap/ngb-component-demo-link.mdx
I update the banner but set ng-bootstrap docs as primary since it fits better with the message and it is also there that you can find additional info on the component's usage.

![image](https://github.com/swisspost/design-system/assets/33580481/03d94f5c-495a-4acd-916a-26f9fe8120d4)

2024-01-23 12:46 UTC, imagoiq commented on packages/documentation/src/shared/nb-bootstrap/ngb-component-demo-link.mdx
In my opinion, I prefer the "old"-first way. Here we are changing the behavior of this alert pattern as not all actions are contextual to each other or to the content, I find it confusing.

2024-01-23 14:15 UTC, alizedebray commented on packages/documentation/src/shared/nb-bootstrap/ngb-component-demo-link.mdx
What do you mean but ""old"-first way"? Do you mean the version where the "See previous documentation" button was on the top right corner?

2024-01-23 14:17 UTC, imagoiq commented on packages/documentation/src/shared/nb-bootstrap/ngb-component-demo-link.mdx
Yes exactly

2024-01-23 14:22 UTC, alizedebray commented on packages/documentation/src/shared/nb-bootstrap/ngb-component-demo-link.mdx
@gfellerph @oliverschuerch What do you think?

2024-01-23 16:30 UTC, gfellerph approved these changes

2024-01-24 07:44 UTC, merged