feat(documentation): Set id/permalink for stories
swisspost/design-system pull request #2603
Opened 2024-02-05 06:27 UTC by imagoiq

Set an id for each story as in https://storybook.js.org/docs/configure/sidebar-and-urls#permalink-to-stories. This allows to separate the URL generation from the display name. The URL is generated with the id and the name of the story with the title. 
You can change the title without changing the id so we can keep a kind of permalink.

2024-02-07 08:48 UTC, alizedebray requested changes
This is great! 👍 

Can you just update the links to the foundation docs using the new id's? 

Also, I'm not sure that using the titles as identifiers is the best solution because there will be discrepancies as soon as we update a component name... I would probably go for a unique id, maybe with an enum somewhere. What do you think?

2024-02-07 10:18 UTC, imagoiq commented
> This is great! 👍
> 
> Can you just update the links to the foundation docs using the new id's?

Good catch!

> Also, I'm not sure that using the titles as identifiers is the best solution because there will be discrepancies as soon as we update a component name... I would probably go for a unique id, maybe with an enum somewhere. What do you think?

I think this is a timeless question between slug vs id/uuid. It can be one or another, or mixed. I'm not really fond of only uuid as it's not user-friendly (and a bit prone to security issue). Using a mix doesn't make it more permanent except if we say that the slug is only here for human (e.g. /bzasdh/accessibility) and is ignored in the redirect process, but this is not how Storybook works, and it doesn't allow that. So it's debatable, perhaps we should have survey in the roundtable meeting?

2024-02-07 14:03 UTC, alizedebray commented
> So it's debatable, perhaps we should have survey in the roundtable meeting?

Sure, let's talk about that with the team

2024-02-08 08:18 UTC, alizedebray commented on packages/documentation/src/stories/components/forms/custom-select/custom-select.stories.ts
> +  id: 'Components/Forms/Custom-Select',
```suggestion
  id: 'Components/Forms/Custom Select',
```

2024-02-08 15:38 UTC, imagoiq commented on packages/documentation/src/stories/components/collapsible/collapsible.stories.ts
> +  const togglerId = `button--${context.id}`;
This is not valid otherwise, as we are targetting an id starting with a number later.

2024-02-08 15:40 UTC, imagoiq commented
It was decided on the roundtable to used exclusively uuid.

2024-02-14 14:48 UTC, alizedebray approved these changes

2024-02-14 15:28 UTC, merged