chore(github): update demo release workflow
swisspost/design-system pull request #2616
Opened 2024-02-07 08:54 UTC by alizedebray

2024-02-07 10:28 UTC, imagoiq approved these changes

2024-02-07 10:28 UTC, imagoiq commented on .github/workflows/release-demo.yaml
>        - name: Install demo app & dependencies
On step "name: Publish demo app to netlify" perhaps you can already duplicate the environment variable for the site ID and rename with something like "NETLIFY_ARCHIVE_SITE_ID" so it's clearer where it is deployed?

2024-02-12 12:27 UTC, gfellerph requested changes
- [x] This PR needs to go on the `release/angular-demo-archive` branch and not to `main`
- [x] I will add a ticket about cleaning up main after this. This workflow as well as the build and deploy demo app workflows can be deleted on main after we migrated
- [x] The netlify site id and token need to be changed because the archive will be deployed to it's own site. This has to be done in this PR and the tokens have to be prefixed like Loïc proposed https://github.com/swisspost/design-system/pull/2616/files#r1481257653

2024-02-15 19:56 UTC, gfellerph requested changes

2024-02-15 19:56 UTC, gfellerph commented on .github/workflows/release-demo.yaml
> +          NETLIFY_ARCHIVE_AUTH_TOKEN: ${{ secrets.NETLIFY_ARCHIVE_AUTH_TOKEN }}
These are used by netlify and are predefined, we just need to update the naming of our secrets.
```suggestion
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_ARCHIVE_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ARCHIVE_AUTH_TOKEN }}
```

2024-02-15 19:56 UTC, gfellerph commented on .github/workflows/release-demo.yaml
> +          netlify link --id $NETLIFY_ARCHIVE_SITE_ID
```suggestion
          netlify link --id $NETLIFY_SITE_ID
```

2024-02-19 07:42 UTC, gfellerph approved these changes

2024-02-19 09:16 UTC, merged