chore(documentation): merge docs pages of card control components into a single one
swisspost/design-system pull request #2847
Opened 2024-03-22 09:22 UTC by oliverschuerch

2024-04-04 09:15 UTC, imagoiq commented on packages/documentation/src/stories/components/forms/card-control/standard-html/card-control-firefox-fallback.sample.ts
> +document.addEventListener('input', e => {
Just by curiosity, did you move the file or recreate it and copy and paste the content or with another method? Github sees it as a new file, not as a move.

2024-04-04 09:20 UTC, imagoiq commented on packages/documentation/tsconfig.json
> +    },
Good idea, we should do it in all other places, can you open an issue, please?

2024-04-04 09:21 UTC, imagoiq commented on packages/documentation/types/storybook.ts
> +
Why this move? I don't really care, but is it your intention or the tooling?

2024-04-05 06:31 UTC, oliverschuerch commented
> Radio type is quite different from the following PR (we should discuss what is the right way): #2774 https://preview-2774--swisspost-design-system-next.netlify.app/?path=/docs/d83829b2-7de2-48d2-be64-07a80c9caef3--docs#validation-messages
> 
> On hover, the SelectedItem color is removed, is it correct?
> 
> Disabled style is as well different from (color + inner circle is filled with white in your version) : #2813 https://preview-2813--swisspost-design-system-next.netlify.app/?path=/docs/151242aa-a074-4a55-a81c-db597c83cdad--docs
> 
> On Firefox, the contrast with the label is not sufficient: ![firefox_b0loouslkD](https://private-user-images.githubusercontent.com/12294151/319528640-c17d5b59-cb74-4866-ac59-6f2c72750352.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNDM4MzgsIm5iZiI6MTcxMjI0MzUzOCwicGF0aCI6Ii8xMjI5NDE1MS8zMTk1Mjg2NDAtYzE3ZDViNTktY2I3NC00ODY2LWFjNTktNmYyYzcyNzUwMzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE1MTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZDVlZTE5N2M3MDdlODBiN2VkNmU2NGJiNjZmYjllNDc1NGJiM2FjZTU4ZmJiNjM2NjZhMzg5N2E0NTlkNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R3owJ2mD9MmFELXpWPPVpWo6cD4bXMjC8A7Do996GhQ)
> 
> Maybe we can talk about all this in the roundtable?

I think I found a satisfying solution for the hcm styles. Please have a look :grinning:

2024-04-15 13:52 UTC, imagoiq requested changes
In HCM on Firefox and hover state, the check has not enough contrast and the border of the checkbox is not visible anymore.

![firefox_HDus3PCFNF](https://github.com/swisspost/design-system/assets/12294151/504d41a6-5bcb-4746-ab9e-888e15731d13)

2024-04-15 13:52 UTC, imagoiq commented on pnpm-lock.yaml
> +        version: 7.6.17(lit@3.1.2)(react-dom@18.2.0)(react@18.2.0)(typescript@5.3.3)(vite@5.1.5)
This will probably resurface the issue that we had last week

2024-04-19 08:06 UTC, oliverschuerch commented
To fix the hcm styles, I've created a new ticket: #2982

2024-04-19 08:20 UTC, gfellerph approved these changes

2024-04-22 08:27 UTC, imagoiq approved these changes

2024-04-24 11:29 UTC, merged