feat(styles, docs, migrations): create the chip component
swisspost/design-system pull request #2855
Opened 2024-03-27 10:54 UTC by alizedebray

2024-04-04 05:37 UTC, oliverschuerch approved these changes

2024-04-09 14:18 UTC, oliverschuerch requested changes
The nested badgesdo not look like in Figma:
![image](https://github.com/swisspost/design-system/assets/9716662/0cfa40d7-634a-42c0-bcb3-dd23d9d429e4)
![image](https://github.com/swisspost/design-system/assets/9716662/101f58a6-7f6e-4bdd-b2c0-46e05b662eaf)
CSS:
![image](https://github.com/swisspost/design-system/assets/9716662/bbd8922a-be94-40f6-bf64-e909a63f4311)

What about the HCM styles, will they be added in a separate ticket?
What about the migration guide, will the information be added in a separate ticket?

2024-04-10 06:30 UTC, alizedebray commented
> The nested badgesdo not look like in Figma:

Rouven was changing them yesterday just after our discussion.
Since this PR is necessary for the v7 release, we decided together with Philipp and Loïc to merge it as soon as the structure is correct and update the styles as a patch later on (ticket #2918)

> What about the HCM styles, will they be added in a separate ticket?

Same as above, the HCM styles are working for now and we can still update them in a future patch  (ticket #2919) 

> What about the migration guide, will the information be added in a separate ticket?

The migration guide is already merged (PR https://github.com/swisspost/design-system/pull/2915)

2024-04-10 07:50 UTC, oliverschuerch approved these changes

2024-04-10 11:38 UTC, merged