feat(styles): invalid message on card-control
swisspost/design-system pull request #2978
Opened 2024-04-18 15:15 UTC by davidritter-dotcom

2024-04-19 06:50 UTC, oliverschuerch commented
There is an open PR for merging the card-control stories. Please do not merge this PR before the other!

2024-05-02 14:20 UTC, oliverschuerch requested changes
Something looks wrong with the icon placement
![image](https://github.com/swisspost/design-system/assets/9716662/7bd8685d-bd91-4084-9671-0569e3fb2161)

Tested on the css-component (web-component looks good).

2024-05-02 17:47 UTC, davidritter-dotcom commented
I've only added the icon in the message on the form elements who don't have an icon inside in this PR, but since the icon inside gets removed everywhere, the icon would need to be added everywhere in the validation message.

2024-05-13 06:21 UTC, oliverschuerch requested changes
Please add a changeset!

2024-05-13 06:21 UTC, oliverschuerch commented on packages/styles/src/components/form-validation.scss
> +  display: inline-flex;
This should be part of the post-card-control.scss.

2024-06-05 07:44 UTC, oliverschuerch reviewed
@davidritter-dotcom did you add the error-message only for the web-component or also for the css-component?
And could we add the error-message also in the default story of both components?

2024-07-03 09:37 UTC, davidritter-dotcom commented
I added the icon for all the invalid- and valid-feedback messages

2024-07-12 11:00 UTC, oliverschuerch approved these changes

2024-07-16 11:54 UTC, merged