chore(components): use the post-collapsible-trigger within the post-accordion-item
swisspost/design-system pull request #3215
Opened 2024-07-04 12:54 UTC by alizedebray

2024-07-09 13:52 UTC, gfellerph commented on packages/components/src/components/post-collapsible-trigger/post-collapsible-trigger.scss
I don't think this is necessary, buttons are not block level elements by default. I'd just not ship any styles at all.

2024-07-23 07:53 UTC, alizedebray commented on .changeset/plenty-experts-admire.md
Remove file

2024-07-23 07:53 UTC, alizedebray commented on .changeset/thin-eyes-join.md
Remove file

2024-07-23 08:20 UTC, oliverschuerch reviewed
@alizedebray did you do something within this PR, which is was not implemented in the v7 patch and the cherry-picked PR for v8?
Because if the answer is "YES", you should add a changeset to this PR ;)

2024-07-23 08:22 UTC, oliverschuerch requested changes

2024-07-23 08:22 UTC, oliverschuerch commented on packages/components/src/components/post-collapsible-trigger/post-collapsible-trigger.tsx
> +import { version } from 'typescript';
Nope!
```suggestion
import { version } from '@root/package.json';
```

2024-07-23 09:24 UTC, oliverschuerch approved these changes

2024-07-23 09:35 UTC, merged