Update select disabled styles
swisspost/design-system pull request #3228
Opened 2024-07-10 07:43 UTC by davidritter-dotcom

2024-07-10 09:32 UTC, alizedebray requested changes
Can you update the styles to match [Figma](https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=7802-33963&m=dev)? When the selection is disabled:
- the label and hint should be `--post-gray-60`
- the chevron icon should be `--post-gray-40` 
- the text should be `--post-gray-60` and not strikethrough

2024-07-11 12:19 UTC, davidritter-dotcom commented
> Can you update the styles to match [Figma](https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=7802-33963&m=dev)? When the selection is disabled:
> 
> * the label and hint should be `--post-gray-60`
> * the chevron icon should be `--post-gray-40`
> * the text should be `--post-gray-60` and not strikethrough

The Design in Figma is already updated and the text is now strikethrough also in the select.

2024-07-15 07:40 UTC, alizedebray approved these changes
If you declare the variables like so:
```
$input-disabled-color: var(--post-gray-60);
$input-disabled-border-color: var(--post-gray-40);
```
Then the other files can remain unchanged, still using `forms.$input-disabled-color` and `forms.$input-disabled-border-color`

The only place where you will have to declare the gray manually is here, because you cannot use a var() in a background URL: 
```
$form-select-disabled-color: forms.$input-disabled-color;
$form-select-indicator-disabled: url('#{icons.get-colored-svg-url('2113', $form-select-disabled-color)}') !default;
```

This approach helps with consistency as you only define the gray twice: once in the form variables and once in the select background.

2024-07-15 07:40 UTC, alizedebray commented on packages/styles/src/variables/components/_forms.scss
> +$input-disabled-color: color.$gray-40; // Design System only
```suggestion
$input-disabled-color: var(--post-gray-60); // Design System only
```

2024-07-15 07:40 UTC, alizedebray commented on packages/styles/src/variables/components/_forms.scss
>  $input-disabled-border-color: color.$gray-40; // Design System only
```suggestion
$input-disabled-border-color: var(--post-gray-40); // Design System only
```

2024-07-16 08:44 UTC, davidritter-dotcom commented
> If you declare the variables like so:
> 
> ```
> $input-disabled-color: var(--post-gray-60);
> $input-disabled-border-color: var(--post-gray-40);
> ```
> 
> Then the other files can remain unchanged, still using `forms.$input-disabled-color` and `forms.$input-disabled-border-color`
> 
> The only place where you will have to declare the gray manually is here, because you cannot use a var() in a background URL:
> 
> ```
> $form-select-disabled-color: forms.$input-disabled-color;
> $form-select-indicator-disabled: url('#{icons.get-colored-svg-url('2113', $form-select-disabled-color)}') !default;
> ```
> 
> This approach helps with consistency as you only define the gray twice: once in the form variables and once in the select background.

The svg doesn't work if there is a css variable behind the sass variable, so I just put a color sass variable for the background URL.

2024-07-17 12:35 UTC, merged