feat(styles, documentation): styles update text input
swisspost/design-system pull request #3229
Opened 2024-07-10 08:19 UTC by davidritter-dotcom

2024-07-18 13:21 UTC, gfellerph commented
@davidritter-dotcom, blocking PR is merged.

2024-07-19 12:47 UTC, oliverschuerch requested changes
- The `textarea` element has still a icon when valid.
  ![image](https://github.com/user-attachments/assets/bb13c1b4-f488-4ebb-b8d7-6e6d6f3cda71)
- The `select` element now has both icons, the one in the background and the one in the error message. This occurs in both states, valid and invalid.
  ![image](https://github.com/user-attachments/assets/b565e833-19cc-4920-91a4-b91106349cae)

2024-07-19 12:47 UTC, oliverschuerch commented on .changeset/gold-rabbits-train.md
> +removed the icon from inside the input and invalid textarea
```suggestion
Removed the icon from inside form-controls (`input`, `select`, `textarea`).
```

2024-07-23 06:28 UTC, oliverschuerch approved these changes

2024-07-23 06:38 UTC, merged