fix(docs): update tabs and control tables
swisspost/design-system pull request #3254
Opened 2024-07-11 12:49 UTC by alizedebray

2024-07-12 11:28 UTC, oliverschuerch requested changes

2024-07-12 11:28 UTC, oliverschuerch commented on packages/documentation/.storybook/styles/components/blocks.scss
This has already been fixed/released: https://design-system.post.ch
Please apply this change only if the bug still persists.

2024-07-12 11:28 UTC, oliverschuerch commented on packages/documentation/.storybook/styles/components/tabs.scss
Nice!
But I still see a horizontal scrollbar.
![image](https://github.com/user-attachments/assets/2210fe9f-e6ff-4ede-b290-eaf627bb04cb)

2024-07-15 06:45 UTC, alizedebray commented on packages/documentation/.storybook/styles/components/tabs.scss
There is another ticket for the scrollbar: https://github.com/swisspost/design-system/issues/3225

2024-07-15 06:49 UTC, alizedebray commented on packages/documentation/.storybook/styles/components/blocks.scss
The issue is still there on the released documentation: 
![image](https://github.com/user-attachments/assets/04bc4333-8218-4d6b-b264-152d7e1b3686)

2024-07-15 12:10 UTC, oliverschuerch approved these changes

2024-07-15 12:11 UTC, oliverschuerch approved these changes

2024-07-15 12:11 UTC, oliverschuerch commented on .changeset/gorgeous-frogs-build.md
> +Added missing borders to control tables and updated tabs to improve visual continuity and readability.
```suggestion
Updated tabs to improve visual continuity and readability.
```

2024-07-15 16:08 UTC, merged