chore(styles): implemented most v2 styles
swisspost/design-system pull request #3558
Opened 2024-09-19 07:29 UTC by schaertim

2024-10-02 15:03 UTC, alizedebray requested changes
Here are the things I noticed: 
- [x] The active switch has no check icon on hover
- [x] The focus outline is 100% wide where it should hug the content
- [x] The focus outline should be rounder when the switch is used with a hidden label
- [x] The disabled styles are not correct 
- [x] The invalid styles seems incorrect as well but you can first ask Sandra to document them in Figma
- [x] I would probably set the label after by default in the docs since it seems to be the default in Figma
- [x] You will have to update [the snapshot story](https://preview-3558--swisspost-design-system-next.netlify.app/iframe.html?id=snapshots--switch&viewMode=story) to use the correct tokens on dark background
- [x] The title of the PR is incorrect it should be like so: "feat(package): summary of your changes"

Do not hesitate to contact me if something is unclear.

2024-10-03 09:51 UTC, schaertim commented on packages/styles/src/components/form-check.scss
Here is the new ticket about the styles separation: #3628

2024-10-03 12:55 UTC, schaertim commented
I implemented the PR feedback, except for these two points:

-  The invalid styles seems incorrect as well but you can first ask Sandra to document them in Figma
- You will have to update [the snapshot story](https://preview-3558--swisspost-design-system-next.netlify.app/iframe.html?id=snapshots--switch&viewMode=story) to use the correct tokens on dark background

Regarding the first one: The validation styles will not be implemented for each component using individual tokens respective to each component. Instead the styling will be done centrally with a designated "validation" token set to be reused in all components requiring validation. I opened a new ticket (#3630) for this which has to be tackled first before completing the switch styling.

And for the second point: Right now it is not clear if the inverted mode will differ from the dark mode. If it does new tokens would have to be created for all inverted colors. Discussions about that decision are still ongoing.

2024-10-08 09:08 UTC, alizedebray requested changes

2024-10-08 09:08 UTC, alizedebray commented on packages/styles/src/components/form-check.scss
> +      @include color-mx.on-dark-background {
Light and dark modes are now handled by the tokens through the semantic layer for modes, you shouldn't have to do anything manually.

2024-10-25 15:47 UTC, alizedebray requested changes
Can you fix the e2e tests please?

2024-11-14 08:49 UTC, closed without merging