[component]: Text link
swisspost/design-system pull request #3590
Opened 2024-09-26 08:44 UTC by alionazherdetska

2024-10-02 14:26 UTC, alizedebray requested changes
Good job 👍 
Do not hesitate to contact me if one of my comments is not clear

2024-10-02 14:26 UTC, alizedebray commented on packages/documentation/src/stories/components/link/link.snapshot.stories.ts
When you create a new snapshot file you also need to create the matching visual regression test here: https://github.com/swisspost/design-system/tree/main/packages/documentation/cypress/snapshots/components
- The `*.snapshot.stories.ts` file creates this page: https://preview-3590--swisspost-design-system-next.netlify.app/iframe.html?id=snapshots--link&viewMode=story
- The `cypress/*.snapshot.ts` files uses this page to take snapshots that are compared every time we release changes

2024-10-02 14:26 UTC, alizedebray commented on packages/documentation/src/stories/components/link/link.snapshot.stories.ts
> +            <div class="${bg} d-flex flex-column gap-regular p-regular mt-regular">
Here you also have to set a `data-color-mode="light"` or `data-color-mode="dark"` attribute so that the correct set of token is used.

2024-10-04 09:41 UTC, alionazherdetska commented on packages/styles/src/elements/link.scss
> +  @include utilities.high-contrast-mode() {
These are the only colors available for link styling: LinkText, ActiveText, and VisitedText. 

That's why I've only added styling for VisitedText, and I plan to use ActiveText to style the last active item in the Breadcrumb component.

![image](https://github.com/user-attachments/assets/6dadf599-37da-4eec-82b9-d32f4445535e)

2024-10-07 13:12 UTC, oliverschuerch requested changes
Please relocate this component so it appears under "Foundations/Typography/Link"!
And also move the files.

2024-10-07 13:12 UTC, oliverschuerch commented on packages/styles/src/elements/link.scss
> +  @include utilities.high-contrast-mode() {
There is also a mixin to do this in the design-system:
````scss
// example
@include high-contrast-mode() {
  color: LinkText;
  
  &:hover {
    color: HighlightText;
  }
}
```

Here you can find he available color names: https://www.w3.org/TR/css-color-4/#css-system-colors

2024-10-14 06:15 UTC, oliverschuerch requested changes

2024-10-14 06:15 UTC, oliverschuerch commented on .idea/indexLayout.xml
This file should be added to the .gitignore file.

2024-10-15 15:11 UTC, alizedebray approved these changes

2024-10-15 15:11 UTC, alizedebray commented on packages/styles/src/elements/anchor.scss
> +  );
It's a detail but I have seen Tim write the focus styles like so and it make it more readable. What do you think? 

```suggestion
  @include utilities.focus-style(
    $offset: tokens.get('link-focus-outline-offset'),
    $width: tokens.get('link-focus-outline-width'),
    $color: tokens.get('link-focus-outline-color'),
    $style: tokens.get('link-focus-outline-style'),
  );
```

2024-10-16 08:20 UTC, oliverschuerch requested changes

2024-10-16 08:20 UTC, oliverschuerch commented on packages/documentation/src/stories/components/link/link.stories.ts
> +  title: 'Typography/Link',
```suggestion
  title: 'Foundations/Typography/Link',
```

2024-10-16 12:45 UTC, oliverschuerch approved these changes

2024-10-16 13:28 UTC, merged