feat(Styles): Updated sizing utility (no tokens)
swisspost/design-system pull request #3679
Opened 2024-10-08 14:01 UTC by myrta2302

2024-10-25 16:08 UTC, alizedebray requested changes

2024-10-25 16:08 UTC, alizedebray commented on packages/documentation/src/stories/utilities/sizing/sizing.stories.ts
>    const maximumHeight = args.maxHeight && args.maxHeight !== 'null' ? `mh-${args.maxHeight}` : '';
This is named "none" in the options (same for all classes bellow) 
```suggestion
  const maximumHeight = args.maxHeight && args.maxHeight !== 'none' ? `mh-${args.maxHeight}` : '';
```

2024-10-25 16:08 UTC, alizedebray commented on packages/styles/src/utilities/_variables.scss
> +      auto: auto,
```suggestion
```

`max-width: auto` is invalid CSS.

2024-11-08 13:05 UTC, alizedebray requested changes

2024-11-08 13:05 UTC, alizedebray commented on packages/documentation/src/stories/utilities/sizing/sizing.docs.mdx
Can you check the headings levels? 

Also, there is a section about responsive classes but the classes are not responsive, can you either remove the section or make the classes responsive.

2024-11-11 11:33 UTC, myrta2302 commented on packages/documentation/src/stories/utilities/sizing/sizing.docs.mdx
ok added

2024-11-11 11:35 UTC, myrta2302 commented on packages/documentation/src/stories/utilities/spacing/spacing.stories.ts
I am not sure how. I tried to go to history and revert any commit that had the spacing file in it to remove it, but i ve probably missed something.

2024-11-12 08:35 UTC, myrta2302 commented on packages/documentation/src/stories/utilities/spacing/spacing.stories.ts
ok found it :)

2024-11-12 08:36 UTC, myrta2302 commented
Still getting the error regarding logo.cy

2024-11-18 10:10 UTC, oliverschuerch commented
naming issues

2024-11-18 10:10 UTC, closed without merging