fix: check props on componentDidLoad
swisspost/design-system pull request #3775
Opened 2024-10-16 20:10 UTC by gfellerph

Delays the prop checks until the last lifecycle hook to give frameworks time to render their props before the check runs.

2024-10-17 13:16 UTC, oliverschuerch commented
Did you already create a cherry pick issue for this?

2024-10-17 21:04 UTC, gfellerph commented
> Did you already create a cherry pick issue for this?

That's not practical before merging this PR. The squash will create a clean commit to cherry-pick.

2024-10-18 07:42 UTC, oliverschuerch requested changes
Fix the failing tests! 😋

2024-10-18 09:17 UTC, gfellerph commented
> Fix the failing tests! 😋

Done!

2024-10-18 09:26 UTC, oliverschuerch approved these changes

2024-10-18 11:17 UTC, merged