feat(styles): implement checkbox styles using tokens
swisspost/design-system pull request #3788
Opened 2024-10-17 12:19 UTC by schaertim

2024-10-24 09:38 UTC, gfellerph requested changes

2024-10-29 11:52 UTC, schaertim commented on packages/styles/src/components/checkbox.scss
I adapted the styles to work with the new markup and changed the storybook examples.

2024-10-31 08:39 UTC, gfellerph requested changes
Just one last change (TM)

2024-10-31 08:39 UTC, gfellerph commented on packages/styles/src/components/_form-check.scss
With a multiline label, the checkbox should stay aligned to the first line of text:

Design:
[<img width="497" alt="image" src="https://github.com/user-attachments/assets/6f6182e4-e400-4757-ba51-533f25fe643a">](https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=416-8193&t=xeLFudZ34eobqjMj-4)

Code:
<img width="625" alt="image" src="https://github.com/user-attachments/assets/ea2a88cf-4a72-4959-b8da-c8a74fa27410">

2024-11-14 08:48 UTC, closed without merging