feat(styles): updated vertical-align utility
swisspost/design-system pull request #3805
Opened 2024-10-23 09:13 UTC by myrta2302

2024-10-25 11:38 UTC, oliverschuerch requested changes

2024-10-28 12:22 UTC, myrta2302 commented on packages/documentation/src/stories/utilities/vertical-align/vertical-align.stories.ts
> +          <td class="align-text-bottom">text-bottom</td>
I actually borrowed these examples:  https://getbootstrap.com/docs/4.3/utilities/vertical-align/

2024-10-28 16:20 UTC, oliverschuerch requested changes

2024-10-28 16:20 UTC, oliverschuerch commented on packages/documentation/src/stories/utilities/vertical-align/vertical-align.snapshot.stories.ts
> +            <span class="align-${align}">${align ? `align-${align}` : 'text'}</span>
We want to show how the image can be aligned with the text, not the other way around.

```suggestion
            <span>${align ? `align-${align}` : 'text'}</span>
            <img class="logo align-${align}" alt="logo" src="/assets/images/logo-swisspost.svg" />
```

2024-10-28 16:20 UTC, oliverschuerch commented on packages/documentation/src/stories/utilities/vertical-align/vertical-align.styles.scss
> +  line-height: 3;
We only want to have these styles applied on the non-table stories.

```suggestion
  :not(:has(table))& {
    border: 1px solid rgb(204, 204, 204);
    line-height: 3;
  }
```

2024-10-28 16:20 UTC, oliverschuerch commented on packages/documentation/src/stories/utilities/vertical-align/vertical-align.styles.scss
> +    height: 64px;
```suggestion
    width: 1rem;
    height: 1rem;
```

2024-11-08 08:37 UTC, oliverschuerch requested changes
Good work, only one CR left.
Tell me when you solved it. Then I will approve your PR 😉

2024-11-11 12:32 UTC, oliverschuerch approved these changes

2024-11-11 12:35 UTC, merged