feat(components): back-to-top button component
swisspost/design-system pull request #3991
Opened 2024-11-14 11:57 UTC by myrta2302

2024-11-15 09:00 UTC, alizedebray commented on .changeset/dull-falcons-hope.md
> +implement back-to-top button
Please make sure to follow the guidelines for the changeset message: it should start with a title-cased verb in past tense and end with a period.

2024-11-15 09:03 UTC, alizedebray commented on packages/documentation/src/stories/components/back-to-top/back-to-top.stories.ts
> +  title: 'Components/Back To Top Button',
```suggestion
  title: 'Components/Back-to-Top Button',
```

2024-11-15 09:10 UTC, alizedebray commented on packages/documentation/src/stories/components/back-to-top/back-to-top.stories.ts
> +  decorators: [
Can you move the decorator and renderer to the meta and reuse it for the snapshot to avoid code duplication?

2024-11-15 09:16 UTC, alizedebray commented on packages/documentation/src/stories/components/back-to-top/back-to-top.docs.mdx
> +  specified threshold, allowing for smooth scrolling back to the top of the page.
It is a good practice to re-use the introduction text from Figma in the docs: https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=517-3594&node-type=frame&t=LZ05qAgicQadYqKo-0

2024-11-15 09:18 UTC, alizedebray commented on packages/documentation/src/stories/components/back-to-top/back-to-top.docs.mdx
> +  <a href="?path=%2Fstory%2F1a1b4cab-d0a8-4b01-bd85-b70e18668cb5--default&amp;full=true">here</a>.
Can you make this more obvious with a button?

2024-11-15 09:18 UTC, alizedebray commented on packages/components/src/components/post-back-to-top/post-back-to-top.tsx
> +          role="button"
This is not needed on a button:
```suggestion
```

2024-11-15 09:20 UTC, alizedebray commented on packages/components/src/components/post-back-to-top/post-back-to-top.tsx
> +          <post-icon aria-hidden={this.belowFold ? 'false' : 'true'} name="3026"></post-icon>
This one is always hidden, this is why  there is a hidden text: 
```suggestion
          <post-icon aria-hidden="true" name="3026"></post-icon>
```

2024-11-15 09:22 UTC, alizedebray commented on packages/components/src/components/post-back-to-top/post-back-to-top.tsx
> +          <span class="visually-hidden">Back To Top Button</span>
For a good accessibility, this text has to be translated to the current language of the page therefore it should be set by the project using your component.

2024-11-15 09:24 UTC, alizedebray commented on packages/components/src/components/post-back-to-top/post-back-to-top.tsx
> +  calcIfIsBelowFold(): boolean {
```suggestion
  isBelowFold(): boolean {
```

2024-11-15 09:28 UTC, alizedebray commented on packages/components/src/animations/back-to-top.ts
Please rename this file to the name of the animation it contains, "slide" maybe?

2024-11-15 09:34 UTC, alizedebray commented on packages/components/src/components/post-back-to-top/post-back-to-top.scss
> +@use '@swisspost/design-system-styles/tokens/components';
Can you check and remove unnecessary imports?

2024-11-20 10:10 UTC, alizedebray requested changes

2024-11-20 10:10 UTC, alizedebray commented on packages/components/src/components/post-back-to-top/post-back-to-top.tsx
> +      <Host>
Please add the version to the host.

2024-11-20 10:10 UTC, alizedebray commented on packages/documentation/src/stories/components/back-to-top/back-to-top.docs.mdx
> +</span>
```suggestion
<a
    className="btn btn-primary"
    target="_blank"
    href={`?path=%2Fstory%2F1a1b4cab-d0a8-4b01-bd85-b70e18668cb5--default&full=true`}
  >
  Back To Top example
</a>
```

2024-11-29 08:37 UTC, alizedebray approved these changes

2024-11-29 08:37 UTC, alizedebray commented on packages/components/src/components/post-back-to-top/post-back-to-top.tsx
> +    }
You can use `checkNonEmpty()` here.

2024-11-29 08:37 UTC, alizedebray commented on packages/components/src/components/post-back-to-top/post-back-to-top.scss
> +@use '@swisspost/design-system-styles/components/button';
This import is not needed:
```suggestion
```

2024-11-29 08:37 UTC, alizedebray commented on packages/components/src/components/post-back-to-top/post-back-to-top.scss
> +@use '@swisspost/design-system-styles/mixins/elevation' as elevation-mx;
You can either import all the mixins individually:
```suggestion
@use '@swisspost/design-system-styles/mixins/button' as button-mx;
@use '@swisspost/design-system-styles/mixins/icons' as icons;
@use '@swisspost/design-system-styles/mixins/utilities';
@use '@swisspost/design-system-styles/mixins/elevation' as elevation-mx;
```

Or use the core file only: 
```suggestion
@use '@swisspost/design-system-styles/core' as post;
```

2024-11-29 09:56 UTC, alizedebray commented on packages/documentation/src/stories/components/back-to-top/back-to-top.stories.ts
> +  title: 'Components/Back To Top Button',
Having 'Button' before will help group all the buttons in the navigation (Also, I’m not sure why I removed the hyphens in my previous comment...)
```suggestion
  title: 'Components/Button Back-to-Top',
```

2024-12-04 13:51 UTC, alizedebray requested changes

2024-12-04 13:51 UTC, alizedebray commented on .changeset/slimy-plums-sniff.md
Is this change intended?

2024-12-04 13:51 UTC, alizedebray commented on .github/workflows/e2e-tests.yaml
Please revert changes made to this file.

2024-12-04 13:51 UTC, alizedebray commented on packages/components/cypress/e2e/back-to-top.cy.ts
> +
Can you uncomment or remove this test?

2024-12-04 13:51 UTC, alizedebray commented on packages/components/package.json
This change also seems unintended, can you please have a look at all the changes and make sure they should be merged?

2024-12-05 11:20 UTC, myrta2302 commented on packages/components/package.json
I reverted / deleted the non relevant files depending on the case.

2024-12-06 14:59 UTC, alizedebray approved these changes

2024-12-09 07:38 UTC, merged