feat(styles): implement simple check list component
swisspost/design-system pull request #4024
Opened 2024-11-19 16:11 UTC by myrta2302

2024-11-20 15:17 UTC, oliverschuerch requested changes

2024-11-20 15:17 UTC, oliverschuerch commented on packages/styles/src/elements/list-check.scss
> +  post-list-check-line-height: 30px
Implement real tokens. Tell @Vandapanda to add them, if they have not been added already.

2024-11-20 15:17 UTC, oliverschuerch commented on packages/styles/src/elements/list-check.scss
> +      content: '';
```suggestion
      display: block;
      content: '';
```

2024-11-21 08:33 UTC, alizedebray commented on packages/styles/src/elements/list-check.scss
> +      margin-bottom: calc(-1 * tokens.get('list-check-text-padding'));
Please use `inline` and `block` properties instead of `right`, `left`, `top`, and `bottom`.

2024-12-02 08:55 UTC, gfellerph requested changes

2024-12-02 08:55 UTC, gfellerph commented on packages/styles/src/elements/list-check.scss
![image](https://github.com/user-attachments/assets/dc1b2b24-afd9-491f-9e9f-d88b2b690a46)

The checks are not responsive, leading to a misalingment on mobile.

2024-12-04 09:09 UTC, gfellerph approved these changes

2024-12-04 09:24 UTC, oliverschuerch commented on packages/styles/src/components/list-check.scss
I think we should use the upcoming list-unstyled mixin.
https://github.com/swisspost/design-system/pull/4097

2024-12-04 09:24 UTC, oliverschuerch approved these changes

2024-12-05 10:34 UTC, merged