feat(component): improve header overflow handling
swisspost/design-system pull request #4273
Opened 2024-12-13 19:23 UTC by alizedebray

2024-12-18 07:53 UTC, gfellerph requested changes
Generally looks nice, but noticed something strange if one element has a very long name 
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/f98bb573-f191-4c73-b655-c78c4dbbe2c0" />

2024-12-19 12:10 UTC, oliverschuerch requested changes
There is no changeset file.

2025-01-07 16:29 UTC, alizedebray commented on packages/components/src/components/post-mainnavigation/post-mainnavigation.scss
> +        line-height: var(--post-core-line-height-100);
First time with me!
Can we discuss this? Currently the whole header is using semantic tokens and I would like to understand why you prefer raw values. Also, I would rather handle this in a separate ticket as it would involve a lot of changes not related to this PR.

2025-01-08 15:51 UTC, gfellerph requested changes
Little hard to show it but if I add a lot of links, I can't scroll to the end of the list, the two megadropdowns are hidden and it won't scroll any further.

![image](https://github.com/user-attachments/assets/d54af4f1-cde1-4991-be03-e1df03ac546f)

2025-01-27 06:56 UTC, oliverschuerch commented on packages/components/src/components/post-header/post-header.tsx
There you go: https://github.com/swisspost/design-system/issues/4527

2025-01-27 08:23 UTC, oliverschuerch requested changes

2025-01-27 08:23 UTC, oliverschuerch commented on packages/components/src/components/post-mainnavigation/post-mainnavigation.scss
> +        line-height: var(--post-core-line-height-100);
Conclusion from our discussion during the todays daily meeting: Avoid using core tokens, instead use sass varialbes (or if avilable use component tokens).

2025-01-27 11:12 UTC, oliverschuerch commented
> @oliverschuerch can you also open a ticket for turning the CSS variables into Sass variables? They are used everywhere in the header, not particularly in this PR. It would be easier to do everything in one go!

I thought we decided to keep component specific css-variables (especially the ones that change on the client side, like `--global-header-height`, etc.) as they are and only replace the usage of core-tokens? 🤔

2025-01-27 11:24 UTC, oliverschuerch requested changes

2025-01-27 11:24 UTC, oliverschuerch commented on packages/components/src/components/post-mainnavigation/post-mainnavigation.scss
> +        line-height: var(--post-core-line-height-100);
By the way, most of these tokens could probably being replaced with utility tokens. Which would be ok for me.

```scss
@use '@swisspost/design-system-styles/core' as post;
@use '@swisspost/design-system-styles/functions/tokens';
@use '@swisspost/design-system-styles/mixins/utilities';

button {
  background: post.$white;
  padding: tokens.get('utility.padding.16', utilities.$post-spacing);
  box-shadow: tokens.get('utility.elevation.500', utilities.$post-elevation);
  line-height: tokens.get('utility.line-height.1', utilities.$ost-typo);
}
```

2025-01-27 14:18 UTC, alizedebray commented
@oliverschuerch That would be the best of both worlds!

2025-01-27 16:03 UTC, oliverschuerch requested changes
PR should contain a changeset

2025-01-28 10:15 UTC, oliverschuerch approved these changes

2025-01-29 16:31 UTC, gfellerph approved these changes

2025-01-29 16:33 UTC, gfellerph reviewed
@alizedebray we should add extensive tests for this feature because the logic is quite complex. We can do this in a separate ticket.

2025-01-30 08:07 UTC, merged