fix(styles): HCM card control checkbox text color
swisspost/design-system pull request #4311
Opened 2024-12-16 16:47 UTC by leagrdv

2024-12-19 17:52 UTC, alizedebray requested changes

2024-12-19 17:52 UTC, alizedebray commented on packages/styles/src/components/segmented-button.scss
> +            border-color: Highlight;
I cannot see this border-color on Firefox.

2024-12-19 17:52 UTC, alizedebray commented on packages/styles/src/components/segmented-button.scss
> +            background-color: SelectedItem;
Just in case: 
```suggestion
            background-color: SelectedItem;
            color: SelectedItemText;
```

2024-12-19 17:52 UTC, alizedebray commented on .changeset/stale-months-dance.md
👍

2025-01-21 17:23 UTC, alizedebray requested changes

2025-01-21 17:23 UTC, alizedebray commented on packages/styles/src/components/segmented-button.scss
> +            border-color: Highlight;
Borders are still missing when hovering over inactive button.

2025-02-11 14:16 UTC, leagrdv commented on packages/styles/src/components/segmented-button.scss
> +            border-color: Highlight;
I updated from color Highlight to SelectedItem as in Firefox, the "Highlight" color is a half transparent blue so it was hard to see. Here's what I get on my side with the new color: 
![Screenshot 2025-02-11 151351](https://github.com/user-attachments/assets/41399a66-abfd-4019-9045-17d4b4ea80ab)

2025-02-14 10:49 UTC, alizedebray approved these changes

2025-02-14 13:02 UTC, merged