fix(styles): fixed visibility of the arrow-icon in HCM
swisspost/design-system pull request #4325
Opened 2024-12-18 06:28 UTC by alionazherdetska

2024-12-18 07:59 UTC, oliverschuerch requested changes
Please add a changeset

2024-12-19 14:12 UTC, oliverschuerch requested changes

2024-12-19 14:12 UTC, oliverschuerch commented on packages/styles/src/components/form-select.scss
In dark hc-mode the arrows contrast to the background is really bad.
Default:
![image](https://github.com/user-attachments/assets/8d5fa98a-5830-497b-9c61-35809f80c018)
Hovered:
![image](https://github.com/user-attachments/assets/5195cfb9-5236-4307-ba79-399937f7a988)

2025-01-10 07:01 UTC, oliverschuerch requested changes

2025-01-10 07:01 UTC, oliverschuerch commented on packages/styles/src/components/form-select.scss
I also recognized, that the text color of the select element does not change on hover (without hcm activated).
This could be a token issue, or we just did not update/use the hover-fg token there.
Please check and fix or contact @Vandapanda to fix it in the token system.

2025-01-13 15:59 UTC, alionazherdetska commented on packages/styles/src/components/form-select.scss
![image](https://github.com/user-attachments/assets/2108fb4e-7f74-4936-bfce-0ee02d8dfa20)
Sandra confirmed that this is the intended behavior.

2025-01-14 15:36 UTC, oliverschuerch approved these changes

2025-01-14 15:36 UTC, merged