feat(documentation): add main storybook
swisspost/design-system pull request #435
Opened 2022-08-29 14:14 UTC by gfellerph

2022-10-07 14:21 UTC, gfellerph commented on packages/documentation/.storybook/main.js
> +      url: "http://localhost:6007"
Updated according to https://storybook.js.org/docs/react/sharing/storybook-composition#compose-storybooks-per-environment

2022-10-07 14:21 UTC, gfellerph commented on packages/documentation/.storybook/main.js
> +      url: "http://localhost:6008"
Updated according to https://storybook.js.org/docs/react/sharing/storybook-composition#compose-storybooks-per-environment

2022-10-07 14:22 UTC, gfellerph commented on package.json
> +	"author": "Swiss Post <oss@post.ch>",
Done

2022-10-07 14:22 UTC, gfellerph commented on .github/workflows/release.yaml
> +        run: pnpm --filter design-system-documentation run chromatic --project-token=${{ secrets.STORYBOOK_TOKEN }}
Done

2022-10-07 14:22 UTC, gfellerph commented on package.json
> +    "intranet-header": "pnpm --filter design-system-components-angular start",
Done, but now I have to type a lot

2022-10-13 10:11 UTC, oliverschuerch requested changes

2022-10-13 10:11 UTC, oliverschuerch commented on .github/workflows/release.yaml
> +        run: pnpm --filter design-system-documentation run chromatic --project-token=${{ secrets.STORYBOOK_TOKEN }}
```suggestion
        run: pnpm --filter design-system-documentation run chromatic --project-token=${{ secrets.CHROMATIC_STORYBOOK_TOKEN }}
```

2022-10-13 11:55 UTC, oliverschuerch approved these changes

2022-10-17 06:52 UTC, merged