feat(documentation): separate icon sets and implement pagination
swisspost/design-system pull request #4351
Opened 2024-12-20 14:22 UTC by oliverschuerch

2025-01-14 15:59 UTC, leagrdv requested changes

2025-01-14 15:59 UTC, leagrdv commented on packages/documentation/src/stories/foundations/icons/search/search-icons.styles.scss
> +    grid-template-columns: repeat(2, 120px);
In desktop, the space around the list elements is great as it makes the layout look more light but I feel like in mobile, it makes the list really long because it's on two columns (so 48 rows) but there is still a lot of space available around.

2025-01-14 15:59 UTC, leagrdv commented on packages/documentation/src/stories/foundations/icons/search/search-icons.styles.scss
> +    .icon {
Icon width should either be a bit bigger or there should be a word break on the icon title because long names break out of the container.
![Screenshot 2025-01-14 165041](https://github.com/user-attachments/assets/f43dd960-4ae6-4e94-af95-402d0c0f5e0e)

2025-01-20 15:56 UTC, oliverschuerch commented on packages/documentation/src/stories/foundations/icons/search/search-icons.styles.scss
> +    grid-template-columns: repeat(2, 120px);
The columns now use fractional values, so the columns always span across the whole available width.

2025-01-20 15:57 UTC, oliverschuerch commented on packages/documentation/src/stories/foundations/icons/search/search-icons.styles.scss
> +    .icon {
The words will now be wrapped to the new line if necessary (with a dash, where the word break happens).

2025-01-21 07:20 UTC, leagrdv reviewed
Approved

2025-01-22 14:29 UTC, gfellerph requested changes
![image](https://github.com/user-attachments/assets/c33e772a-8229-42cb-a318-a5f652d07206)

Seems like the new icons are rendered too bold.

Tested on Chrome and Edge, Firefox looks ok.

Firefox:
![image](https://github.com/user-attachments/assets/9c001006-dd4e-437a-a957-5cb60288b5c7)

2025-01-24 10:19 UTC, leagrdv approved these changes

2025-01-24 10:26 UTC, gfellerph approved these changes

2025-01-24 11:21 UTC, merged