chore(documentation, styles): text utilities
swisspost/design-system pull request #4360
Opened 2024-12-24 16:22 UTC by leagrdv

2025-01-07 16:08 UTC, alizedebray requested changes

2025-01-07 16:08 UTC, alizedebray commented on packages/styles/src/utilities/_variables.scss
> +$font-family-sans-serif: var(--post-device-font-family-default);
Device layer tokens (`post-device-*`) are not meant to be used directly, it seems like you are missing a utility token here. You can ask @Vandapanda to create it, it would be nice to have tokens for the font weights and line heights as well. They might be useful for the tailwind output anyways.

2025-01-09 07:28 UTC, leagrdv commented on packages/documentation/.storybook/styles/components/typo.scss
> -    .font-sans-serif {
I simply removed the class from the storybook styles because `.font-sans-serif` is generated by the variables utility already.

2025-01-23 08:27 UTC, gfellerph commented
On hold until available line-height options are clear, @leagrdv clarifies this with @rouvenpost.

2025-01-31 08:04 UTC, alizedebray approved these changes

2025-01-31 08:50 UTC, merged