feat(migration): add migration documentation
swisspost/design-system pull request #472
Opened 2022-09-21 13:08 UTC by oliverschuerch

The documentation is based on the internal ChangeLog wiki page.

2022-09-29 11:52 UTC, gfellerph requested changes
Great work! There's just one more thing:

- [x] The topic teaser below the migration instructions is broken

2022-09-30 10:31 UTC, oliverschuerch commented on packages/demo/src/app/home/home.component.scss
> +@use '@swisspost/design-system-styles/basics' as *;
Mainly it fixed some header font-size issues. But it's not essential.
Should we remove it?

2022-09-30 13:25 UTC, gfellerph requested changes

2022-09-30 13:25 UTC, gfellerph commented on packages/demo/src/app/home/home.component.scss
> +.form-check-label {
```suggestion
.bubble-tea .form-check-label {
```

These styles also apply for the switches which should not be grayed out when active.

2022-09-30 13:40 UTC, gfellerph approved these changes

2022-10-03 06:51 UTC, merged