refactor: add package-json script naming convention and clean up scripts and workflows
swisspost/design-system pull request #550
Opened 2022-10-04 15:04 UTC by oliverschuerch

2022-10-04 19:32 UTC, gfellerph requested changes

2022-10-04 19:32 UTC, gfellerph commented on CONTRIBUTING.md
> +- A script name uses only letters, numbers and semi-colons.
```suggestion
- A script name uses only letters, dashes and colons.
```

2022-10-04 19:32 UTC, gfellerph commented on CONTRIBUTING.md
> +- A script name short and descriptive.
```suggestion
- A script name is short and descriptive.
```

2022-10-04 19:32 UTC, gfellerph commented on CONTRIBUTING.md
> +- A non default script name is post-fix which describes it's special characteristica (e.g. `lint:fix`).
```suggestion
- A non default script name is postfixed with it's characteristics (e.g. `lint:fix`).
```

2022-10-04 19:32 UTC, gfellerph commented on CONTRIBUTING.md
> +- A non default script name for a specific tool, is pre-fixed with the toolname (e.g. `storybook:serve`, `storybook:bulid`, etc.).
```suggestion
- A non default script name for a specific tool is prefixed with the tool name (e.g. `storybook:serve`, `storybook:bulid`, etc.).
```

2022-10-04 19:32 UTC, gfellerph commented on CONTRIBUTING.md
> +- A non default script name can contain more than one semi-colon (e.g. `lint:fix:dry`, `stencil:test:watch`, etc.).
```suggestion
- A non default script name can contain more than one colon (e.g. `lint:fix:dry`, `stencil:test:watch`, etc.).
```

2022-10-05 06:50 UTC, gfellerph approved these changes

2022-10-05 14:48 UTC, gfellerph requested changes
Is 82119b1d0e02fa57964041f485e0f6bc1d6f0d60 really necessary? GitHub Actions should be detected by pnpm as a CI environment.

2022-10-05 14:48 UTC, gfellerph commented on .github/workflows/test.yaml
> +        uses: swisspost/design-system/.github/actions/setup-pnpm@refactor/549-refactor-packagejson-scripts
```suggestion
        uses: swisspost/design-system/.github/actions/setup-pnpm@main
```

2022-10-05 15:10 UTC, oliverschuerch commented
@gfellerph your absolutly right. Github Workflows should be detected as CI and so the --frozen-lockfile flag is automatically set to true. By including the flag in the Workflows, I just wanted to make ist absolutly clear.
If you think it's redundant, I can remove it again.

2022-10-05 19:34 UTC, gfellerph approved these changes

2022-10-05 20:10 UTC, merged