docs(migration): add enhancements and improvements
swisspost/design-system pull request #590
Opened 2022-10-14 12:43 UTC by oliverschuerch

2022-10-14 12:46 UTC, swisspost-devs commented
Preview environments are getting posted here, as soon as they are ready!

2022-10-17 09:42 UTC, gfellerph requested changes

2022-10-17 09:42 UTC, gfellerph commented on packages/demo/src/app/home/home.component.html
> +                          <span class="change-badge bg-danger">breaking</span> Removed <span class="highlight">src/lic/cwf-licene.scss</span> file.
```suggestion
                          <span class="change-badge bg-danger">breaking</span> Removed <span class="highlight">src/lic/cwf-license.scss</span> file.
```

2022-10-17 09:42 UTC, gfellerph commented on packages/demo/src/app/home/home.component.html
> +                      </label>
```suggestion
                      </label>
                      <p class="info">Read more on namespaces at the <a href="https://sass-lang.com/blog/the-module-system-is-launched">sass module system intro</a>.</p>
```

2022-10-17 09:42 UTC, gfellerph commented on packages/demo/src/app/bootstrap/components/accordion/accordion-demo-page/accordion-demo-page.component.html
> +      The detail summary styles have been removed due to some issues.
```suggestion
      The detail summary styles have been removed due to <a href="https://adrianroselli.com/2019/04/details-summary-are-not-insert-control-here.html">accessibility issues with the &lt;summary&gt; element</a>.
```

2022-10-18 15:26 UTC, gfellerph commented on packages/demo/src/app/home/home.component.html
> +              highlight="npm install @swisspost/design-system-migrations"
```suggestion
              highlight="npm install --save-dev @swisspost/design-system-migrations"
```

2022-10-19 11:09 UTC, gfellerph approved these changes

2022-10-20 09:20 UTC, merged