refactor: integrate migrations package in styles package
swisspost/design-system pull request #611
Opened 2022-10-21 09:17 UTC by oliverschuerch

2022-10-21 09:21 UTC, swisspost-devs commented
Preview environments are getting posted here, as soon as they are ready!

2022-10-21 14:27 UTC, gfellerph requested changes

2022-10-21 14:27 UTC, gfellerph commented on .changeset/green-games-design.md
> +Adds Migrations to Styles package.
```suggestion
Adds Angular migration Schematics to the @swisspost/design-system-styles package. These migrations will be automatically triggered when using `ng update @swisspost/design-system-styles` in your Angular project. For more information, have a look at the [migration guide](https://design-system.post.ch/).
```

2022-10-21 14:27 UTC, gfellerph commented on packages/styles/README.md
> +Schematics are used to transform a software project by adapting it to current Design System Styles.
```suggestion
Schematics are used to transform an Angular software project by adapting it to current Design System Styles.
```

2022-10-21 14:27 UTC, gfellerph commented on packages/styles/README.md
> +To execute the migrations please follow our [migration-guide](https://design-system.post.ch/).
```suggestion
To execute the migrations please follow our [migration guide](https://design-system.post.ch/).
```

2022-10-24 10:06 UTC, gfellerph approved these changes

2022-10-24 10:11 UTC, merged