feat(styles-migration): create migrations with the new cheerio util
swisspost/design-system pull request #687
Opened 2022-11-02 13:37 UTC by oliverschuerch

2022-11-02 13:41 UTC, swisspost-devs commented
Preview environments are getting posted here, as soon as they are ready!

2022-11-07 07:36 UTC, gfellerph requested changes

2022-11-07 07:36 UTC, gfellerph commented on packages/styles/schematics/utils/dom/migration-rule.ts
> +              const distElement = $outputElements.filter((_i, element) => $(element).data('cheerio-id') === source.id).first().toString();
```suggestion
              const distElement = $outputElements.find((_i, element) => $(element).data('cheerio-id') === source.id).toString();
```

2022-11-07 07:36 UTC, gfellerph commented on packages/demo/src/app/home/home.component.html
> +                        <span class="change-badge bg-danger">breaking</span> Background classes such as <code>.bg-[colorname]</code>, now also automatically define the inner <span class="highlight">t
That entry is suspicious. A `text-color` class never existed. `text-auto` did and has an automatic migration available which is already documented.

2022-11-09 15:48 UTC, gfellerph approved these changes

2022-11-10 10:28 UTC, merged