feat(documentation): add form-select stories
swisspost/design-system pull request #831
Opened 2022-11-30 16:28 UTC by oliverschuerch

2022-11-30 16:31 UTC, swisspost-devs commented
Preview environments are getting posted here, as soon as they are ready!

2022-12-08 07:04 UTC, gfellerph requested changes

2022-12-08 08:05 UTC, oliverschuerch commented on packages/documentation/.storybook/preview-head.html
> +  }
To fullfill the AA standards a rating from 4.5 would be enough and we're very close to this here.

I would prefer something like I implemented here. It's how bootstrap is doing it, and their docs are well styled/formatted and pretty nice to read.

If we want a more github like styling of inline code elements, I'd prefer a light color an a dark background;
![image](https://user-images.githubusercontent.com/9716662/206392326-129afb18-fff2-4d22-8ba8-5b9b111330da.png)
![image](https://user-images.githubusercontent.com/9716662/206392200-088dd6c8-aac5-4e33-bddb-918b08b502f0.png)

What do you think?

2022-12-08 08:29 UTC, oliverschuerch commented on packages/documentation/src/stories/components/select/select.docs.mdx
> +However, it is possible to deactivate the initially selected option as well. This option can then not be reselected after the user changed the selection once.
This is only the halfe truth...
As a user of a screen reader which is focusing a select field I would probably not press "space" or "enter" to open the dropdown menu of the select field but only select one of them with the arrow keys. In this case, the screenreader does not say "option 1 of 5" but only reads the option label (e.g. "option 1").

And with all this accessability topcis in mind, I think we should not forget, that about 75-95% of or users are not blind or visually impaired. All the seeing people should be able to visually recognize, that the option is disabled.

And in my opinion, disabled options in a select or a checkbox/radio button group are definitly a common use cases.

2022-12-08 08:57 UTC, gfellerph commented on packages/documentation/src/stories/components/select/select.docs.mdx
> +However, it is possible to deactivate the initially selected option as well. This option can then not be reselected after the user changed the selection once.
What would be a reason to disable options and how are you communicating this to the user?

2022-12-08 09:02 UTC, gfellerph commented on packages/documentation/.storybook/preview-head.html
> +  }
It's personal preference, but I'm not a fan of the bootstrap style and I like the light variant better as it's a more subtle.

2022-12-08 09:04 UTC, oliverschuerch commented on packages/documentation/src/stories/components/select/select.stories.tsx
> +    ] as ISelectOption[],
This is only the halfe truth...
As a "blind" person which is focusing a select field I would probably not press "space" or "enter" to open the dropdown menu of the select field but only select one of them with the arrow keys. In this case, the screenreader does not say "option 1 of 5" but only reads the option label (e.g. "option 1").

And with all this accessability topcis in mind, I think we should not forget, that about 75-95% of or users are not blind or visually impaired.

And in my opinion, disabled options in a select, a checkbox or a radio button group are definitly a common use cases.

2022-12-08 09:39 UTC, oliverschuerch commented on packages/documentation/src/stories/components/select/select.docs.mdx
> +However, it is possible to deactivate the initially selected option as well. This option can then not be reselected after the user changed the selection once.
It's not about reasons, it's about giving developers all the options.
Of course, we can remove this example, but the developers out there know about the `disabled` attribute and after all, we implement appropriate styles for it.
So what would be the reason to hide this information?

As long as our styles package is not up to date to properly work with the `readonly` attribute (which could be the accessable alternative to the `disabled` attribute), I'll still prefer to show this example.

And yes, we can tell the developers to not disable options dynamically, but just omit them completely.
But how would you communicate that runtime change to disabled users?
In my opinion, the problem stays the same, but one of the cases is a better approach for non disabled users.

2022-12-08 10:13 UTC, oliverschuerch commented on packages/documentation/src/stories/components/select/select.docs.mdx
> +However, it is possible to deactivate the initially selected option as well. This option can then not be reselected after the user changed the selection once.
We decided to just integrate a hint, that the disabled state on form-fields has some accessability issues and a link to the describing part in the accessability docs page.

2022-12-08 13:38 UTC, oliverschuerch commented on packages/documentation/src/stories/components/select/select.docs.mdx
> +However, it is possible to deactivate the initially selected option as well. This option can then not be reselected after the user changed the selection once.
There was one sentence from you @gfellerph that make me look with an other angle on the docs:
"We do only document our Design System, not how HTML or some elements work".

Thats why I removed the option-stories completly. As every developer should be able to find out, how to set the value of a `select` element, without the need of our documentation to show this.

2022-12-08 13:39 UTC, oliverschuerch commented on packages/documentation/src/stories/components/select/select.stories.tsx
> +    ] as ISelectOption[],
Totally removed this in the newest version ;)

2022-12-08 13:54 UTC, gfellerph approved these changes
Just typos and text changes, otherwise nice story!

2022-12-08 13:54 UTC, gfellerph commented on packages/documentation/src/stories/components/select/select.docs.mdx
> +  Do not use this classes on a <code>select</code> elements wrapped within a{' '}
```suggestion
  Do not use this classes on <code>select</code> elements wrapped within a{' '}
```

2022-12-08 13:54 UTC, gfellerph commented on packages/documentation/src/stories/components/select/select.stories.tsx
> +      description: '<p>Render the component with or without a visible label.</p><div className="alert alert-info alert-sm">There are accessability issues with hidden labels.<br/>Please read our <a hr
```suggestion
      description: '<p>Render the component with or without a visible label.</p><div className="alert alert-info alert-sm">There are accessibility issues with hidden labels.<br/>Please read our <a href="/?path=/story/foundations-accessibility--page#labels">labels accessibility guide</a>.</div>',
```

2022-12-08 13:54 UTC, gfellerph commented on packages/documentation/src/stories/components/select/select.stories.tsx
> +      description: '<p>When set to `true`, disables the component\'s functionality and places it in a disabled state.</p><div className="alert alert-info alert-sm">There are accessability issues with
```suggestion
      description: '<p>When set to `true`, disables the component\'s functionality and places it in a disabled state.</p><div className="alert alert-info alert-sm">There are accessibility issues with the disabled state.<br/>Please read our <a href="/?path=/docs/foundations-accessibility--page#disabled-state">disabled state accessibility guide</a>.</div>',
```

2022-12-08 13:54 UTC, gfellerph commented on packages/documentation/src/stories/foundation/accessability.stories.mdx
> +  title="Foundations/Accessability"
```suggestion
  title="Foundations/Accessibility"
```

2022-12-08 13:54 UTC, gfellerph commented on packages/documentation/src/stories/foundation/accessability.stories.mdx
> +# Accessability
```suggestion
# Accessibility
```

2022-12-08 13:54 UTC, gfellerph commented on packages/documentation/src/stories/foundation/accessability.stories.mdx
> +  TODO: write accessability page
```suggestion
  TODO: write accessibility page
```

2022-12-08 13:54 UTC, gfellerph commented on packages/documentation/src/stories/foundation/accessability.stories.mdx
> +TODO: write accessability guide about form labels (visible and invisible), aria-label, ...
```suggestion
TODO: write accessibility guide about form labels (visible and invisible), aria-label, ...
```

2022-12-08 13:54 UTC, gfellerph commented on packages/documentation/src/stories/foundation/accessability.stories.mdx
> +TODO: write accessability guide about disabled states on input, textarea, select, select-options,
```suggestion
TODO: write accessibility guide about disabled states on input, textarea, select, select-options,
```

2022-12-08 14:41 UTC, merged