feat(documentation): add form-check stories
swisspost/design-system pull request #857
Opened 2022-12-07 14:22 UTC by oliverschuerch

2022-12-07 14:25 UTC, swisspost-devs commented
Preview environments are getting posted here, as soon as they are ready!

2022-12-08 10:15 UTC, gfellerph requested changes

2022-12-08 10:21 UTC, gfellerph commented on packages/documentation/src/stories/components/checkbox/checkbox.stories.tsx
> +  </div>
Can you wrap this example in a `<fieldset><legend>...</legend> ...checkboxes... </fieldset>` structure to have a label for the group of checkboxes?

This should probably also be mentioned in the docs (https://www.accessibility-developer-guide.com/examples/forms/grouping-with-fieldset-legend/).

2022-12-08 13:51 UTC, oliverschuerch commented on packages/documentation/src/stories/components/checkbox/checkbox.stories.tsx
> +    },
But we are already communicating this in the current documentation... 🤔

2022-12-08 13:59 UTC, gfellerph commented on packages/documentation/src/stories/components/checkbox/checkbox.stories.tsx
> +    },
I know, it's not ideal. I don't think we can ensure that all components work on all backgrounds so I'd like to concentrate on the dark mode and if we accidentally make something work on other backgrounds that's a bonus.

2022-12-13 08:35 UTC, gfellerph requested changes
Not sure if intentional, when toggling between indeterminate, unchecked and checked, the visual state will stay indeterminate. I think the controls should correctly represent the visual state.

2022-12-13 12:55 UTC, alizedebray requested changes
It would be nice to:
- [x] Add a control to toggle the visibility of the fieldset legend

Apply some changes requested in the form switch PR:
- [x] Update documentation wording and correct typos
- [x] Remove `<p>` and `<div>` elements from argument descriptions
- [ ] Use `class` instead of `className` in HTML strings
- [ ] Show form feedback controls only when necessary

2022-12-14 10:31 UTC, oliverschuerch commented on packages/documentation/src/stories/components/checkbox/checkbox.docs.mdx
> +Normally a checkbox input can only have two states: `checked` or `unchecked`. They can have any value, but they either submit that value (checked) or don't (unchecked) with a form submission.
I would prefer to leave this text as is, if this is ok for you?
Source: https://bootstrap-vue.org/docs/components/form-checkbox#indeterminate-tri-state-support

2022-12-14 10:31 UTC, oliverschuerch commented on packages/documentation/src/stories/components/checkbox/checkbox.docs.mdx
> +Visually, there are three states a checkbox can be in: `checked`, `unchecked`, or `indeterminate`.<br/>
I would prefer to leave this text as is, if this is ok for you?
Source: https://bootstrap-vue.org/docs/components/form-checkbox#indeterminate-tri-state-support

2022-12-14 10:31 UTC, oliverschuerch commented on packages/documentation/src/stories/components/checkbox/checkbox.docs.mdx
> +The `indeterminate` state is visual only. The checkbox is still either **checked** or **unchecked** as a value. That means the visual `indeterminate` state masks the real value of the checkbox. A pos
I would prefer to leave this text as is, if this is ok for you?
Source: https://bootstrap-vue.org/docs/components/form-checkbox#indeterminate-tri-state-support

2022-12-15 05:38 UTC, gfellerph approved these changes
Amazing! It's coming together nicely.

2022-12-15 07:40 UTC, merged