feat(documentation): add range stories
swisspost/design-system pull request #902
Opened 2022-12-21 10:33 UTC by oliverschuerch

2022-12-21 10:36 UTC, swisspost-devs commented
Preview environments are getting posted here, as soon as they are ready!

2022-12-22 11:49 UTC, alizedebray requested changes

2022-12-22 11:49 UTC, alizedebray commented on packages/documentation/src/stories/components/range/range.stories.tsx
> +export const Boundaries: Story = Template.bind({});
``
```suggestion
export const Boundaries: Story = Template.bind({});
Boundaries.storyName  = 'Min, Max & Steps';
```

2022-12-22 11:49 UTC, alizedebray commented on packages/documentation/src/stories/components/range/range.docs.mdx
> +`range` inputs have implicit values for `min` and `max` (0 and 100), respectively and by default, snap to integer values.
```suggestion
Range inputs have implicit values for `min` and `max` (0 and 100 respectively), and snap to integer values by default.
```

2022-12-23 07:42 UTC, alizedebray approved these changes

2022-12-23 08:18 UTC, merged